<?php

namespace Database\Seeders;

use App\Models\Multban\Empresa\Empresa;
use App\Models\Multban\Empresa\EmpresaParam;
use App\Models\Multban\Empresa\EmpresaTaxpos;
use App\Models\Multban\Produto\Produto;
use App\Models\Multban\ProgramaPts\ProgramaPts;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DadosMestreSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //Artisan::call('permission:create-permission-routes');
        Empresa::insert([
            ## EMPRESA 1
            [
                'emp_id' => 1,
                'emp_cnpj' => '04889602000138',
                'emp_sts' => 'AT',
                'emp_wl' => 'x',
                'emp_comwl' => '10.00',
                'emp_wlde' => null,
                'emp_privlbl' => null,
                'emp_ie' => '654785326598',
                'emp_im' => null,
                'emp_rzsoc' => 'Teste @01 é White Label',
                'emp_nfant' => 'Teste @01 é White Label',
                'emp_nmult' => 'Teste @01 é WL',
                'emp_ratv' => '2',
                'emp_frqmst' => null,
                'emp_frq' => null,
                'emp_frqcmp' => null,
                'emp_altlmt' => null,
                'emp_integra' => 'x',
                'emp_reemb' => 'x',
                'emp_checkb' => 'x',
                'emp_tpbolet' => 'BTC',
                'emp_checkm' => 'x',
                'tp_plano' => 'COMP',
                'emp_checkc' => 'x',
                'emp_adqrnt' => 'AFINZ',
                'emp_meiocom' => 'GG',
                'vlr_imp' => '1500.00',
                'dtvenc_imp' => '20250528',
                'cond_pgto' => '2',
                'vlr_mens' => '150.00',
                'dtvenc_mens' => '20250528',
                'emp_cep' => '09850010',
                'emp_end' => 'Rua Orestes Suster',
                'emp_endnum' => '285',
                'emp_endcmp' => 'Empresa',
                'emp_endbair' => 'Dos Casa',
                'emp_endcid' => '2305',
                'emp_endest' => 'SP',
                'emp_endpais' => 'BR',
                'emp_resplg' => 'Responsável Legal',
                'emp_emailrp' => 'rl@gmail.com',
                'emp_celrp' => '11983355470',
                'emp_respcm' => 'Contato Comercial',
                'emp_emailcm' => 'cc@gmail.com',
                'emp_celcm' => '11983355470',
                'emp_respfi' => 'Contato Financeiro',
                'emp_emailfi' => 'cf@gmail.com',
                'emp_celfi' => '11983355470',
                'emp_pagweb' => 'www.teste02.com.br',
                'emp_rdsoc' => 'teste02.com.br',
                'logo_path' => null,
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'modificador' => '1',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            ## EMPRESA 2
            [
                'emp_id' => 2,
                'emp_cnpj' => '56468651346843',
                'emp_sts' => 'AT',
                'emp_wl' => null,
                'emp_comwl' => '0.00',
                'emp_wlde' => null,
                'emp_privlbl' => 'x',
                'emp_ie' => '321321635416',
                'emp_im' => null,
                'emp_rzsoc' => 'Teste @02 é Private Label',
                'emp_nfant' => 'Teste @02 é Private Label',
                'emp_nmult' => 'Teste @02 é PL',
                'emp_ratv' => '2',
                'emp_frqmst' => null,
                'emp_frq' => null,
                'emp_frqcmp' => null,
                'emp_altlmt' => null,
                'emp_integra' => 'x',
                'emp_reemb' => 'x',
                'emp_checkb' => 'x',
                'emp_tpbolet' => 'BTC',
                'emp_checkm' => 'x',
                'tp_plano' => 'COMP',
                'emp_checkc' => 'x',
                'emp_adqrnt' => 'AFINZ',
                'emp_meiocom' => 'GG',
                'vlr_imp' => '1500.00',
                'dtvenc_imp' => '20250528',
                'cond_pgto' => '2',
                'vlr_mens' => '150.00',
                'dtvenc_mens' => '20250528',
                'emp_cep' => '09850010',
                'emp_end' => 'Rua Orestes Suster',
                'emp_endnum' => '285',
                'emp_endcmp' => 'Empresa',
                'emp_endbair' => 'Dos Casa',
                'emp_endcid' => '2305',
                'emp_endest' => 'SP',
                'emp_endpais' => 'BR',
                'emp_resplg' => 'Responsável Legal',
                'emp_emailrp' => 'rl@gmail.com',
                'emp_celrp' => '11983355470',
                'emp_respcm' => 'Contato Comercial',
                'emp_emailcm' => 'cc@gmail.com',
                'emp_celcm' => '11983355470',
                'emp_respfi' => 'Contato Financeiro',
                'emp_emailfi' => 'cf@gmail.com',
                'emp_celfi' => '11983355470',
                'emp_pagweb' => 'www.teste02.com.br',
                'emp_rdsoc' => 'teste02.com.br',
                'logo_path' => null,
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'modificador' => '1',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            ## EMPRESA 3
            [
                'emp_id' => 3,
                'emp_cnpj' => '26489753125698',
                'emp_sts' => 'AT',
                'emp_wl' => null,
                'emp_comwl' => '0.00',
                'emp_wlde' => null,
                'emp_privlbl' => null,
                'emp_ie' => '598975321659',
                'emp_im' => null,
                'emp_rzsoc' => 'Teste @03 é Franqueadora',
                'emp_nfant' => 'Teste @03 é Private Label',
                'emp_nmult' => 'Teste @03 é Fqd',
                'emp_ratv' => '2',
                'emp_frqmst' => null,
                'emp_frq' => 'x',
                'emp_frqcmp' => null,
                'emp_altlmt' => null,
                'emp_integra' => 'x',
                'emp_reemb' => 'x',
                'emp_checkb' => 'x',
                'emp_tpbolet' => 'BTC',
                'emp_checkm' => 'x',
                'tp_plano' => 'COMP',
                'emp_checkc' => 'x',
                'emp_adqrnt' => 'AFINZ',
                'emp_meiocom' => 'GG',
                'vlr_imp' => '1500.00',
                'dtvenc_imp' => '20250528',
                'cond_pgto' => '2',
                'vlr_mens' => '150.00',
                'dtvenc_mens' => '20250528',
                'emp_cep' => '09850010',
                'emp_end' => 'Rua Orestes Suster',
                'emp_endnum' => '285',
                'emp_endcmp' => 'Empresa',
                'emp_endbair' => 'Dos Casa',
                'emp_endcid' => '2305',
                'emp_endest' => 'SP',
                'emp_endpais' => 'BR',
                'emp_resplg' => 'Responsável Legal',
                'emp_emailrp' => 'rl@gmail.com',
                'emp_celrp' => '11983355470',
                'emp_respcm' => 'Contato Comercial',
                'emp_emailcm' => 'cc@gmail.com',
                'emp_celcm' => '11983355470',
                'emp_respfi' => 'Contato Financeiro',
                'emp_emailfi' => 'cf@gmail.com',
                'emp_celfi' => '11983355470',
                'emp_pagweb' => 'www.teste02.com.br',
                'emp_rdsoc' => 'teste02.com.br',
                'logo_path' => 'logos\empresa_4\logo.jpeg',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'modificador' => '1',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            ## EMPRESA 4
            [
                'emp_id' => 4,
                'emp_cnpj' => '56489365784203',
                'emp_sts' => 'AT',
                'emp_wl' => null,
                'emp_comwl' => '0.00',
                'emp_wlde' => null,
                'emp_privlbl' => null,
                'emp_ie' => '156983647854',
                'emp_im' => null,
                'emp_rzsoc' => 'Teste @04 é Franqueada',
                'emp_nfant' => 'Teste @04 é Franqueada',
                'emp_nmult' => 'Teste @04 é Fqa',
                'emp_ratv' => '2',
                'emp_frqmst' => 3,
                'emp_frq' => null,
                'emp_frqcmp' => 'x',
                'emp_altlmt' => null,
                'emp_integra' => 'x',
                'emp_reemb' => 'x',
                'emp_checkb' => 'x',
                'emp_tpbolet' => 'BTC',
                'emp_checkm' => 'x',
                'tp_plano' => 'COMP',
                'emp_checkc' => 'x',
                'emp_adqrnt' => 'AFINZ',
                'emp_meiocom' => 'GG',
                'vlr_imp' => '1500.00',
                'dtvenc_imp' => '20250528',
                'cond_pgto' => '2',
                'vlr_mens' => '150.00',
                'dtvenc_mens' => '20250528',
                'emp_cep' => '09850010',
                'emp_end' => 'Rua Orestes Suster',
                'emp_endnum' => '285',
                'emp_endcmp' => 'Empresa',
                'emp_endbair' => 'Dos Casa',
                'emp_endcid' => '2305',
                'emp_endest' => 'SP',
                'emp_endpais' => 'BR',
                'emp_resplg' => 'Responsável Legal',
                'emp_emailrp' => 'rl@gmail.com',
                'emp_celrp' => '11983355470',
                'emp_respcm' => 'Contato Comercial',
                'emp_emailcm' => 'cc@gmail.com',
                'emp_celcm' => '11983355470',
                'emp_respfi' => 'Contato Financeiro',
                'emp_emailfi' => 'cf@gmail.com',
                'emp_celfi' => '11983355470',
                'emp_pagweb' => 'www.teste02.com.br',
                'emp_rdsoc' => 'teste02.com.br',
                'logo_path' => null,
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'modificador' => '1',
                'dthr_ch' => '2025-05-28 21:17:07',
            ]
        ]);

        $tbdm_empresa_param = EmpresaParam::insert([
            ## EMPRESA 1
            [
                'emp_id' => 1,
                'emp_destvlr' => 'CTBA',
                'emp_cdgbc' => '213',
                'emp_agbc' => '0001-9',
                'emp_ccbc' => '123456-5',
                'emp_pix' => '12324654687498',
                'emp_seller' => 'dh1sd6h4d31x',
                'emp_cdgbcs' => '341',
                'emp_agbcs' => '0001-6',
                'emp_ccbcs' => '45698-5',
                'emp_pixs' => '65654g6s46465sd',
                'emp_sellers' => 'sd5g6sa54gv6xz',
                'blt_ctr' => 'x',
                'tax_blt' => '2.1',
                'blt_parclib' => '10',
                'lib_cnscore' => 'x',
                'intervalo_mes' => '3',
                'qtde_cns_freem' => '10',
                'qtde_cns_cntrm' => '15',
                'card_posctr' => 'x',
                'card_posparc' => '24',
                'vlr_pix' => '0.70',
                'vlr_boleto' => '2.10',
                'vlr_bolepix' => '2.20',
                'cob_mltjr_atr' => 'x',
                'perc_mlt_atr' => '2.1',
                'perc_jrs_atr' => '2.2',
                'perc_com_mltjr' => '50.0',
                'dias_inat_card' => '15',
                'isnt_pixblt' => '500.00',
                'parc_cjuros' => 'x',
                'parc_jr_deprc' => '3',
                'tax_jrsparc' => '1.0',
                'parc_com_jrs' => '2.0',
                'card_prectr' => 'x',
                'tax_pre' => '5.99',
                'card_giftctr' => 'x',
                'tax_gift' => '5.99',
                'card_fidctr' => 'x',
                'tax_fid' => '5.99',
                'pp_particular' => 'x',
                'pp_franquia' => 'x',
                'pp_mult' => 'x',
                'pp_cashback' => 'x',
                'antecip_ctr' => 'x',
                'tax_antmult' => '2.0',
                'tax_antfundo' => '2.0',
                'perc_rec_ant' => '52.0',
                'inad_semrisco' => 'x',
                'fndant_cdgbc' => '213',
                'fndant_agbc' => '0001-9',
                'fndant_ccbc' => '3216345-5',
                'fndant_pix' => 'sdfgs6dfg46sd4gf',
                'fndant_seller' => 'sd65f46s54f65sd4f',
                'antecip_auto' => 'x',
                'ant_auto_srvd' => '15',
                'ant_auto_prdvo' => '15',
                'ant_auto_prdvd' => '15',
                'ant_blktit' => 'x',
                'ant_titpdv' => 'x',
                'cobsrv_atv' => 'x',
                'cobsrv_diasatr' => '15',
                'cobsrv_multa' => '5.0',
                'cobsrv_juros' => '5.0',
                'tax_cobsrv_adm' => '5.0',
                'tax_cobsrv_juss' => '5.0',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            ## EMPRESA 2
            [
                'emp_id' => 2,
                'emp_destvlr' => 'CTBA',
                'emp_cdgbc' => '213',
                'emp_agbc' => '0001-9',
                'emp_ccbc' => '123456-5',
                'emp_pix' => '12324654687498',
                'emp_seller' => 'dh1sd6h4d31x',
                'emp_cdgbcs' => '341',
                'emp_agbcs' => '0001-6',
                'emp_ccbcs' => '45698-5',
                'emp_pixs' => '65654g6s46465sd',
                'emp_sellers' => 'sd5g6sa54gv6xz',
                'blt_ctr' => 'x',
                'tax_blt' => '2.1',
                'blt_parclib' => '10',
                'lib_cnscore' => 'x',
                'intervalo_mes' => '3',
                'qtde_cns_freem' => '10',
                'qtde_cns_cntrm' => '15',
                'card_posctr' => 'x',
                'card_posparc' => '24',
                'vlr_pix' => '0.70',
                'vlr_boleto' => '2.10',
                'vlr_bolepix' => '2.20',
                'cob_mltjr_atr' => 'x',
                'perc_mlt_atr' => '2.1',
                'perc_jrs_atr' => '2.2',
                'perc_com_mltjr' => '50.0',
                'dias_inat_card' => '15',
                'isnt_pixblt' => '500.00',
                'parc_cjuros' => 'x',
                'parc_jr_deprc' => '3',
                'tax_jrsparc' => '1.0',
                'parc_com_jrs' => '2.0',
                'card_prectr' => 'x',
                'tax_pre' => '5.99',
                'card_giftctr' => 'x',
                'tax_gift' => '5.99',
                'card_fidctr' => 'x',
                'tax_fid' => '5.99',
                'pp_particular' => 'x',
                'pp_franquia' => 'x',
                'pp_mult' => 'x',
                'pp_cashback' => 'x',
                'antecip_ctr' => 'x',
                'tax_antmult' => '2.0',
                'tax_antfundo' => '2.0',
                'perc_rec_ant' => '52.0',
                'inad_semrisco' => 'x',
                'fndant_cdgbc' => '213',
                'fndant_agbc' => '0001-9',
                'fndant_ccbc' => '3216345-5',
                'fndant_pix' => 'sdfgs6dfg46sd4gf',
                'fndant_seller' => 'sd65f46s54f65sd4f',
                'antecip_auto' => 'x',
                'ant_auto_srvd' => '15',
                'ant_auto_prdvo' => '15',
                'ant_auto_prdvd' => '15',
                'ant_blktit' => 'x',
                'ant_titpdv' => 'x',
                'cobsrv_atv' => 'x',
                'cobsrv_diasatr' => '15',
                'cobsrv_multa' => '5.0',
                'cobsrv_juros' => '5.0',
                'tax_cobsrv_adm' => '5.0',
                'tax_cobsrv_juss' => '5.0',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            ## EMPRESA 3
            [
                'emp_id' => 3,
                'emp_destvlr' => 'CTBA',
                'emp_cdgbc' => '213',
                'emp_agbc' => '0001-9',
                'emp_ccbc' => '123456-5',
                'emp_pix' => '12324654687498',
                'emp_seller' => 'dh1sd6h4d31x',
                'emp_cdgbcs' => '341',
                'emp_agbcs' => '0001-6',
                'emp_ccbcs' => '45698-5',
                'emp_pixs' => '65654g6s46465sd',
                'emp_sellers' => 'sd5g6sa54gv6xz',
                'blt_ctr' => 'x',
                'tax_blt' => '2.1',
                'blt_parclib' => '10',
                'lib_cnscore' => 'x',
                'intervalo_mes' => '3',
                'qtde_cns_freem' => '10',
                'qtde_cns_cntrm' => '15',
                'card_posctr' => 'x',
                'card_posparc' => '24',
                'vlr_pix' => '0.70',
                'vlr_boleto' => '2.10',
                'vlr_bolepix' => '2.20',
                'cob_mltjr_atr' => 'x',
                'perc_mlt_atr' => '2.1',
                'perc_jrs_atr' => '2.2',
                'perc_com_mltjr' => '50.0',
                'dias_inat_card' => '15',
                'isnt_pixblt' => '500.00',
                'parc_cjuros' => 'x',
                'parc_jr_deprc' => '3',
                'tax_jrsparc' => '1.0',
                'parc_com_jrs' => '2.0',
                'card_prectr' => 'x',
                'tax_pre' => '5.99',
                'card_giftctr' => 'x',
                'tax_gift' => '5.99',
                'card_fidctr' => 'x',
                'tax_fid' => '5.99',
                'pp_particular' => 'x',
                'pp_franquia' => 'x',
                'pp_mult' => 'x',
                'pp_cashback' => 'x',
                'antecip_ctr' => 'x',
                'tax_antmult' => '2.0',
                'tax_antfundo' => '2.0',
                'perc_rec_ant' => '52.0',
                'inad_semrisco' => 'x',
                'fndant_cdgbc' => '213',
                'fndant_agbc' => '0001-9',
                'fndant_ccbc' => '3216345-5',
                'fndant_pix' => 'sdfgs6dfg46sd4gf',
                'fndant_seller' => 'sd65f46s54f65sd4f',
                'antecip_auto' => 'x',
                'ant_auto_srvd' => '15',
                'ant_auto_prdvo' => '15',
                'ant_auto_prdvd' => '15',
                'ant_blktit' => 'x',
                'ant_titpdv' => 'x',
                'cobsrv_atv' => 'x',
                'cobsrv_diasatr' => '15',
                'cobsrv_multa' => '5.0',
                'cobsrv_juros' => '5.0',
                'tax_cobsrv_adm' => '5.0',
                'tax_cobsrv_juss' => '5.0',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            ## EMPRESA 4
            [
                'emp_id' => 4,
                'emp_destvlr' => 'CTBA',
                'emp_cdgbc' => '213',
                'emp_agbc' => '0001-9',
                'emp_ccbc' => '123456-5',
                'emp_pix' => '12324654687498',
                'emp_seller' => 'dh1sd6h4d31x',
                'emp_cdgbcs' => '341',
                'emp_agbcs' => '0001-6',
                'emp_ccbcs' => '45698-5',
                'emp_pixs' => '65654g6s46465sd',
                'emp_sellers' => 'sd5g6sa54gv6xz',
                'blt_ctr' => 'x',
                'tax_blt' => '2.1',
                'blt_parclib' => '10',
                'lib_cnscore' => 'x',
                'intervalo_mes' => '3',
                'qtde_cns_freem' => '10',
                'qtde_cns_cntrm' => '15',
                'card_posctr' => 'x',
                'card_posparc' => '24',
                'vlr_pix' => '0.70',
                'vlr_boleto' => '2.10',
                'vlr_bolepix' => '2.20',
                'cob_mltjr_atr' => 'x',
                'perc_mlt_atr' => '2.1',
                'perc_jrs_atr' => '2.2',
                'perc_com_mltjr' => '50.0',
                'dias_inat_card' => '15',
                'isnt_pixblt' => '500.00',
                'parc_cjuros' => 'x',
                'parc_jr_deprc' => '3',
                'tax_jrsparc' => '1.0',
                'parc_com_jrs' => '2.0',
                'card_prectr' => 'x',
                'tax_pre' => '5.99',
                'card_giftctr' => 'x',
                'tax_gift' => '5.99',
                'card_fidctr' => 'x',
                'tax_fid' => '5.99',
                'pp_particular' => 'x',
                'pp_franquia' => 'x',
                'pp_mult' => 'x',
                'pp_cashback' => 'x',
                'antecip_ctr' => 'x',
                'tax_antmult' => '2.0',
                'tax_antfundo' => '2.0',
                'perc_rec_ant' => '52.0',
                'inad_semrisco' => 'x',
                'fndant_cdgbc' => '213',
                'fndant_agbc' => '0001-9',
                'fndant_ccbc' => '3216345-5',
                'fndant_pix' => 'sdfgs6dfg46sd4gf',
                'fndant_seller' => 'sd65f46s54f65sd4f',
                'antecip_auto' => 'x',
                'ant_auto_srvd' => '15',
                'ant_auto_prdvo' => '15',
                'ant_auto_prdvd' => '15',
                'ant_blktit' => 'x',
                'ant_titpdv' => 'x',
                'cobsrv_atv' => 'x',
                'cobsrv_diasatr' => '15',
                'cobsrv_multa' => '5.0',
                'cobsrv_juros' => '5.0',
                'tax_cobsrv_adm' => '5.0',
                'tax_cobsrv_juss' => '5.0',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'dthr_ch' => '2025-05-28 21:17:07',
            ]
        ]);

        $tbdm_empresa_taxpos = EmpresaTaxpos::insert([
            ## EMPRESA 1
            [
                'tax_id' => 1,
                'emp_id' => 1,
                'tax_categ' => 'P30D',
                'parc_de' => '1',
                'parc_ate' => '12',
                'tax' => '1.99',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            [
                'tax_id' => 2,
                'emp_id' => 1,
                'tax_categ' => 'P30D',
                'parc_de' => '13',
                'parc_ate' => '24',
                'tax' => '2.99',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            [
                'tax_id' => 3,
                'emp_id' => 1,
                'tax_categ' => 'P60D',
                'parc_de' => '1',
                'parc_ate' => '24',
                'tax' => '2.99',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            [
                'tax_id' => 4,
                'emp_id' => 1,
                'tax_categ' => 'P90D',
                'parc_de' => '1',
                'parc_ate' => '24',
                'tax' => '3.99',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            [
                'tax_id' => 5,
                'emp_id' => 1,
                'tax_categ' => 'PVST',
                'parc_de' => '1',
                'parc_ate' => '24',
                'tax' => '1.99',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            ## EMPRESA 2
            [
                'tax_id' => 6,
                'emp_id' => 2,
                'tax_categ' => 'P30D',
                'parc_de' => '1',
                'parc_ate' => '24',
                'tax' => '1.99',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            [
                'tax_id' => 7,
                'emp_id' => 2,
                'tax_categ' => 'P60D',
                'parc_de' => '1',
                'parc_ate' => '24',
                'tax' => '2.99',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            [
                'tax_id' => 8,
                'emp_id' => 2,
                'tax_categ' => 'P90D',
                'parc_de' => '1',
                'parc_ate' => '24',
                'tax' => '3.99',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            [
                'tax_id' => 9,
                'emp_id' => 2,
                'tax_categ' => 'PVST',
                'parc_de' => '1',
                'parc_ate' => '24',
                'tax' => '1.99',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            ## EMPRESA 3
            [
                'tax_id' => 10,
                'emp_id' => 3,
                'tax_categ' => 'P30D',
                'parc_de' => '1',
                'parc_ate' => '24',
                'tax' => '1.99',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            [
                'tax_id' => 11,
                'emp_id' => 3,
                'tax_categ' => 'P60D',
                'parc_de' => '1',
                'parc_ate' => '24',
                'tax' => '2.99',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            [
                'tax_id' => 12,
                'emp_id' => 3,
                'tax_categ' => 'P90D',
                'parc_de' => '1',
                'parc_ate' => '24',
                'tax' => '3.99',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            [
                'tax_id' => 13,
                'emp_id' => 3,
                'tax_categ' => 'PVST',
                'parc_de' => '1',
                'parc_ate' => '24',
                'tax' => '1.99',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            ## EMPRESA 4
            [
                'tax_id' => 14,
                'emp_id' => 4,
                'tax_categ' => 'P30D',
                'parc_de' => '1',
                'parc_ate' => '24',
                'tax' => '1.99',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            [
                'tax_id' => 15,
                'emp_id' => 4,
                'tax_categ' => 'P60D',
                'parc_de' => '1',
                'parc_ate' => '24',
                'tax' => '2.99',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            [
                'tax_id' => 16,
                'emp_id' => 4,
                'tax_categ' => 'P90D',
                'parc_de' => '1',
                'parc_ate' => '24',
                'tax' => '3.99',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            [
                'tax_id' => 17,
                'emp_id' => 4,
                'tax_categ' => 'PVST',
                'parc_de' => '1',
                'parc_ate' => '24',
                'tax' => '1.99',
                'criador' => '1',
                'dthr_cr' => '2025-05-28 21:17:07',
                'dthr_ch' => '2025-05-28 21:17:07',
            ]
        ]);

        $tbdm_langu = [
            ['langu' => 'PORT', "langu_desc" => "Português"],
        ];

        DB::table('tbdm_langu')->insert($tbdm_langu);

        $userstatus = [
            ['user_sts' => 'AT', 'langu' => 'PORT', 'user_sts_desc' => 'Ativo'],
            ['user_sts' => 'IN', 'langu' => 'PORT', 'user_sts_desc' => 'Inativo'],
            ['user_sts' => 'EX', 'langu' => 'PORT', 'user_sts_desc' => 'Excluído'],
            ['user_sts' => 'BL', 'langu' => 'PORT', 'user_sts_desc' => 'Bloqueado'],
        ];

        DB::table('tbdm_userstatus')->insert($userstatus);

        $userfunc = [
            ['user_func_grp' => 'adm', 'user_func' => '1', 'langu' => 'PORT', 'user_func_desc' => 'Administrativo'],
            ['user_func_grp' => 'consulta', 'user_func' => '2', 'langu' => 'PORT', 'user_func_desc' => 'Cirugião'],
            ['user_func_grp' => 'adm', 'user_func' => '3', 'langu' => 'PORT', 'user_func_desc' => 'Contador'],
            ['user_func_grp' => 'adm', 'user_func' => '4', 'langu' => 'PORT', 'user_func_desc' => 'Coordenador'],
            ['user_func_grp' => 'consulta', 'user_func' => '5', 'langu' => 'PORT', 'user_func_desc' => 'Dentista'],
            ['user_func_grp' => 'adm', 'user_func' => '6', 'langu' => 'PORT', 'user_func_desc' => 'Enfermeiro'],
            ['user_func_grp' => 'adm', 'user_func' => '7', 'langu' => 'PORT', 'user_func_desc' => 'Farmacêutico'],
            ['user_func_grp' => 'adm', 'user_func' => '8', 'langu' => 'PORT', 'user_func_desc' => 'Financeiro'],
            ['user_func_grp' => 'consulta', 'user_func' => '9', 'langu' => 'PORT', 'user_func_desc' => 'Fisioterapeuta'],
            ['user_func_grp' => 'consulta', 'user_func' => '10', 'langu' => 'PORT', 'user_func_desc' => 'Fonoaudiólogo'],
            ['user_func_grp' => 'adm', 'user_func' => '11', 'langu' => 'PORT', 'user_func_desc' => 'Gerente'],
            ['user_func_grp' => 'consulta', 'user_func' => '12', 'langu' => 'PORT', 'user_func_desc' => 'Médico'],
            ['user_func_grp' => 'consulta', 'user_func' => '13', 'langu' => 'PORT', 'user_func_desc' => 'Nutricionista'],
            ['user_func_grp' => 'consulta', 'user_func' => '14', 'langu' => 'PORT', 'user_func_desc' => 'Odontologista'],
            ['user_func_grp' => 'consulta', 'user_func' => '15', 'langu' => 'PORT', 'user_func_desc' => 'Psicólogo'],
            ['user_func_grp' => 'adm', 'user_func' => '16', 'langu' => 'PORT', 'user_func_desc' => 'Recepcionista'],
            ['user_func_grp' => 'adm', 'user_func' => '17', 'langu' => 'PORT', 'user_func_desc' => 'RH'],
            ['user_func_grp' => 'adm', 'user_func' => '18', 'langu' => 'PORT', 'user_func_desc' => 'Secretária'],
            ['user_func_grp' => 'adm', 'user_func' => '19', 'langu' => 'PORT', 'user_func_desc' => 'Sócio / Proprietário'],
            ['user_func_grp' => 'adm', 'user_func' => '20', 'langu' => 'PORT', 'user_func_desc' => 'Supervisor'],
            ['user_func_grp' => 'consulta', 'user_func' => '21', 'langu' => 'PORT', 'user_func_desc' => 'Terapeuta'],
            ['user_func_grp' => 'adm', 'user_func' => '22', 'langu' => 'PORT', 'user_func_desc' => 'TI'],
        ];

        DB::table('tbdm_userfunc')->insert($userfunc);

        $empstatus = [
            ['emp_sts' => 'AT', 'langu' => 'PORT', 'emp_sts_desc' => 'Ativo'],
            ['emp_sts' => 'IN', 'langu' => 'PORT', 'emp_sts_desc' => 'Inativo'],
            ['emp_sts' => 'EX', 'langu' => 'PORT', 'emp_sts_desc' => 'Excluído'],
            ['emp_sts' => 'BL', 'langu' => 'PORT', 'emp_sts_desc' => 'Bloqueado'],
            ['emp_sts' => 'NA', 'langu' => 'PORT', 'emp_sts_desc' => 'Em Análise'],
            ['emp_sts' => 'ID', 'langu' => 'PORT', 'emp_sts_desc' => 'Inadimplente'],
            ['emp_sts' => 'ON', 'langu' => 'PORT', 'emp_sts_desc' => 'OnBoarding'],
            ['emp_sts' => 'AC', 'langu' => 'PORT', 'emp_sts_desc' => 'Abertura de Conta'],
            ['emp_sts' => 'FT', 'langu' => 'PORT', 'emp_sts_desc' => 'Faturado'],
        ];

        DB::table('tbdm_empstatus')->insert($empstatus);

        $emp_ratv = [
            ['emp_ratv' => '1', 'langu' => 'PORT', 'emp_ratv_desc' => 'Assistência Social'],
            ['emp_ratv' => '2', 'langu' => 'PORT', 'emp_ratv_desc' => 'Clínicas'],
            ['emp_ratv' => '3', 'langu' => 'PORT', 'emp_ratv_desc' => 'Comércio Atacadista'],
            ['emp_ratv' => '4', 'langu' => 'PORT', 'emp_ratv_desc' => 'Comércio Varejista'],
            ['emp_ratv' => '5', 'langu' => 'PORT', 'emp_ratv_desc' => 'Hospitais'],
            ['emp_ratv' => '6', 'langu' => 'PORT', 'emp_ratv_desc' => 'Indústria'],
            ['emp_ratv' => '7', 'langu' => 'PORT', 'emp_ratv_desc' => 'Laboratórios'],
            ['emp_ratv' => '8', 'langu' => 'PORT', 'emp_ratv_desc' => 'Odontologia'],
            ['emp_ratv' => '9', 'langu' => 'PORT', 'emp_ratv_desc' => 'Oftalmologia'],
            ['emp_ratv' => '10', 'langu' => 'PORT', 'emp_ratv_desc' => 'Serviços Terapêuticos'],
            ['emp_ratv' => '11', 'langu' => 'PORT', 'emp_ratv_desc' => 'Outros'],
        ];

        DB::table('tbdm_emp_ratv')->insert($emp_ratv);

        $bnccode = [
            ['cdgbc' => '1', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco do Brasil S.A.'],
            ['cdgbc' => '3', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco da Amazonia S.A.'],
            ['cdgbc' => '4', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Do Nordeste Do Brasil S.A.'],
            ['cdgbc' => '7', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Nacional De Desenvolvimento Economico E Social'],
            ['cdgbc' => '10', 'langu' => 'PORT', 'cdgbc_desc' => 'Credicoamo Credito Rural Cooperativa'],
            ['cdgbc' => '11', 'langu' => 'PORT', 'cdgbc_desc' => 'Credit Suisse Hedging-Griffo Corretora De Valores S.A'],
            ['cdgbc' => '12', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Inbursa S.A.'],
            ['cdgbc' => '14', 'langu' => 'PORT', 'cdgbc_desc' => 'State Street Brasil S.A. – Banco Comercial'],
            ['cdgbc' => '15', 'langu' => 'PORT', 'cdgbc_desc' => 'Ubs Brasil Corretora de Câmbio, Títulos e Valores Mobiliários S.A.'],
            ['cdgbc' => '16', 'langu' => 'PORT', 'cdgbc_desc' => 'Cooperativa de Crédito Mutuo dos Despachantes de Trânsito de Santa Catarina e Rio Grande do Sul'],
            ['cdgbc' => '17', 'langu' => 'PORT', 'cdgbc_desc' => 'Bny Mellon Banco S.A.'],
            ['cdgbc' => '18', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Tricury S.A.'],
            ['cdgbc' => '21', 'langu' => 'PORT', 'cdgbc_desc' => 'Banestes S.A. Banco Do Estado do Espirito Santo'],
            ['cdgbc' => '24', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Bandepe S.A.'],
            ['cdgbc' => '25', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Alfa S.A.'],
            ['cdgbc' => '29', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Itaú Consignado S.A.'],
            ['cdgbc' => '31', 'langu' => 'PORT', 'cdgbc_desc' => 'Código Banco Beg S.A.'],
            ['cdgbc' => '33', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Santander (Brasil) S.A.'],
            ['cdgbc' => '36', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Bradesco BBI S.A.'],
            ['cdgbc' => '37', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Do Estado Do Pará S.A.'],
            ['cdgbc' => '40', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Cargill S.A.'],
            ['cdgbc' => '41', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Do Estado Do Rio Grande Do Sul S.A. (BANRISUL)'],
            ['cdgbc' => '47', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Do Estado De Sergipe S.A.'],
            ['cdgbc' => '51', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco de Desenvolvimento do Espírito Santo S.A.'],
            ['cdgbc' => '60', 'langu' => 'PORT', 'cdgbc_desc' => 'Confidence Corretora De Câmbio S.A.'],
            ['cdgbc' => '62', 'langu' => 'PORT', 'cdgbc_desc' => 'Hipercard Banco Múltiplo S.A.'],
            ['cdgbc' => '63', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Bradescard S.A.'],
            ['cdgbc' => '64', 'langu' => 'PORT', 'cdgbc_desc' => 'Goldman Sachs Do Brasil Banco Multiplo S.A.'],
            ['cdgbc' => '65', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Andbank (Brasil) S.A.'],
            ['cdgbc' => '66', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Morgan Stanley S.A.'],
            ['cdgbc' => '69', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Crefisa S.A.'],
            ['cdgbc' => '70', 'langu' => 'PORT', 'cdgbc_desc' => 'BrB – Banco De Brasilia S.A.'],
            ['cdgbc' => '74', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco J. Safra S.A.'],
            ['cdgbc' => '75', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Abn Amro S.A.'],
            ['cdgbc' => '76', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Kdb Do Brasil S.A.'],
            ['cdgbc' => '77', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Inter S.A.'],
            ['cdgbc' => '78', 'langu' => 'PORT', 'cdgbc_desc' => 'Haitong Banco De Investimento Do Brasil S.A.'],
            ['cdgbc' => '79', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Original Do Agronegócio S.A.'],
            ['cdgbc' => '80', 'langu' => 'PORT', 'cdgbc_desc' => 'B&T Corretora De Cambio Ltda.'],
            ['cdgbc' => '81', 'langu' => 'PORT', 'cdgbc_desc' => 'Bancoseguro S.A.'],
            ['cdgbc' => '82', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Topázio S.A.'],
            ['cdgbc' => '83', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco da China Brasil S.A.'],
            ['cdgbc' => '84', 'langu' => 'PORT', 'cdgbc_desc' => 'Uniprime Norte Do Paraná – Coop de Economia e Crédito Mútuo Dos Médicos'],
            ['cdgbc' => '85', 'langu' => 'PORT', 'cdgbc_desc' => 'Cooperativa Central De Crédito – Ailos'],
            ['cdgbc' => '88', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Randon S.A.'],
            ['cdgbc' => '89', 'langu' => 'PORT', 'cdgbc_desc' => 'Credisan Cooperativa De Crédito'],
            ['cdgbc' => '91', 'langu' => 'PORT', 'cdgbc_desc' => 'Central De Cooperativas De Economia E Crédito Mútuo Do Estado Do Rio Grande Do S'],
            ['cdgbc' => '92', 'langu' => 'PORT', 'cdgbc_desc' => 'Brk S.A. Crédito'],
            ['cdgbc' => '94', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Finaxis S.A.'],
            ['cdgbc' => '95', 'langu' => 'PORT', 'cdgbc_desc' => 'Travelex Banco De Câmbio S.A.'],
            ['cdgbc' => '96', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco B3 S.A.'],
            ['cdgbc' => '97', 'langu' => 'PORT', 'cdgbc_desc' => 'Credisis – Central De Cooperativas De Crédito Ltda.'],
            ['cdgbc' => '98', 'langu' => 'PORT', 'cdgbc_desc' => 'Credialiança Cooperativa De Crédito Rural'],
            ['cdgbc' => '99', 'langu' => 'PORT', 'cdgbc_desc' => 'Uniprime Central – Central Interestadual De Cooperativas de Credito Ltda.'],
            ['cdgbc' => '100', 'langu' => 'PORT', 'cdgbc_desc' => 'Planner Corretora de Valores S.A.'],
            ['cdgbc' => '101', 'langu' => 'PORT', 'cdgbc_desc' => 'Renascenca Distribuidora de Títulos e Valores Mobiliários Ltda'],
            ['cdgbc' => '102', 'langu' => 'PORT', 'cdgbc_desc' => 'Xp Investimentos Corretora de Câmbio,Títulos d Valores Mobiliários S/A'],
            ['cdgbc' => '104', 'langu' => 'PORT', 'cdgbc_desc' => 'Caixa Econômica Federal'],
            ['cdgbc' => '105', 'langu' => 'PORT', 'cdgbc_desc' => 'Lecca Crédito'],
            ['cdgbc' => '107', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Bocom Bbm S.A.'],
            ['cdgbc' => '108', 'langu' => 'PORT', 'cdgbc_desc' => 'Portocred S.A. – Credito'],
            ['cdgbc' => '111', 'langu' => 'PORT', 'cdgbc_desc' => 'Oliveira Trust Distribuidora de Títulos e Valores Mobiliarios S.A.'],
            ['cdgbc' => '113', 'langu' => 'PORT', 'cdgbc_desc' => 'Magliano S.A. Corretora De Cambio E Valores Mobiliarios'],
            ['cdgbc' => '114', 'langu' => 'PORT', 'cdgbc_desc' => 'Central Cooperativa De Crédito No Estado Do Espírito Santo – Cecoop'],
            ['cdgbc' => '117', 'langu' => 'PORT', 'cdgbc_desc' => 'Advanced Corretora De Câmbio Ltda'],
            ['cdgbc' => '119', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Western Union Do Brasil S.A.'],
            ['cdgbc' => '120', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Rodobens S.A.'],
            ['cdgbc' => '121', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Agibank S.A.'],
            ['cdgbc' => '122', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Bradesco Berj S.A.'],
            ['cdgbc' => '124', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Woori Bank Do Brasil S.A.'],
            ['cdgbc' => '125', 'langu' => 'PORT', 'cdgbc_desc' => 'Plural S.A. Banco Múltiplo'],
            ['cdgbc' => '126', 'langu' => 'PORT', 'cdgbc_desc' => 'Br Partners Banco De Investimento S.A.'],
            ['cdgbc' => '127', 'langu' => 'PORT', 'cdgbc_desc' => 'Codepe Corretora De Valores E Câmbio S.A.'],
            ['cdgbc' => '128', 'langu' => 'PORT', 'cdgbc_desc' => 'Ms Bank S.A. Banco De Câmbio'],
            ['cdgbc' => '129', 'langu' => 'PORT', 'cdgbc_desc' => 'Ubs Brasil Banco de Investimento S.A.'],
            ['cdgbc' => '130', 'langu' => 'PORT', 'cdgbc_desc' => 'Caruana S.A. – Sociedade De Crédito'],
            ['cdgbc' => '131', 'langu' => 'PORT', 'cdgbc_desc' => 'Tullett Prebon Brasil Corretora de Valores e Câmbio Ltda'],
            ['cdgbc' => '132', 'langu' => 'PORT', 'cdgbc_desc' => 'Icbc Do Brasil Banco Múltiplo S.A.'],
            ['cdgbc' => '133', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Cresol – Confederação Nacional Das Cooperativas Centrais De Crédito e Economia Familiar e Solidária'],
            ['cdgbc' => '134', 'langu' => 'PORT', 'cdgbc_desc' => 'Bgc Liquidez Distribuidora De Títulos E Valores Mobiliários Ltda'],
            ['cdgbc' => '136', 'langu' => 'PORT', 'cdgbc_desc' => 'Unicred Do Brasil – Confederação Nacional Das Cooperativas Centrais Unicred Ltda.'],
            ['cdgbc' => '138', 'langu' => 'PORT', 'cdgbc_desc' => 'Get Money Corretora De Câmbio S.A.'],
            ['cdgbc' => '139', 'langu' => 'PORT', 'cdgbc_desc' => 'Intesa Sanpaolo Brasil S.A. – Banco Múltiplo'],
            ['cdgbc' => '140', 'langu' => 'PORT', 'cdgbc_desc' => 'Easynvest – Título Corretora De Valores Sa'],
            ['cdgbc' => '142', 'langu' => 'PORT', 'cdgbc_desc' => 'Broker Brasil Corretora De Câmbio Ltda.'],
            ['cdgbc' => '143', 'langu' => 'PORT', 'cdgbc_desc' => 'Treviso Corretora De Câmbio S.A.'],
            ['cdgbc' => '144', 'langu' => 'PORT', 'cdgbc_desc' => 'Bexs Banco De Câmbio S/A'],
            ['cdgbc' => '145', 'langu' => 'PORT', 'cdgbc_desc' => 'Levycam – Corretora De Cambio E Valores Ltda.'],
            ['cdgbc' => '146', 'langu' => 'PORT', 'cdgbc_desc' => 'Guitta Corretora De Cambio Ltda.'],
            ['cdgbc' => '149', 'langu' => 'PORT', 'cdgbc_desc' => 'Facta Financeira S.A. – Crédito Financiamento e Investimento'],
            ['cdgbc' => '157', 'langu' => 'PORT', 'cdgbc_desc' => 'Icap Do Brasil Corretora De Títulos E Valores Mobiliários Ltda.'],
            ['cdgbc' => '159', 'langu' => 'PORT', 'cdgbc_desc' => 'Casa Do Crédito S.A. Sociedade De Crédito Ao Microempreendedor'],
            ['cdgbc' => '163', 'langu' => 'PORT', 'cdgbc_desc' => 'Commerzbank Brasil S.A. – Banco Múltiplo'],
            ['cdgbc' => '169', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Olé Consignado S.A.'],
            ['cdgbc' => '172', 'langu' => 'PORT', 'cdgbc_desc' => 'Albatross Ccv S.A'],
            ['cdgbc' => '173', 'langu' => 'PORT', 'cdgbc_desc' => 'Brl Trust Distribuidora De Títulos E Valores Mobiliários S.A.'],
            ['cdgbc' => '174', 'langu' => 'PORT', 'cdgbc_desc' => 'Pefisa S.A. – Crédito'],
            ['cdgbc' => '177', 'langu' => 'PORT', 'cdgbc_desc' => 'Guide Investimentos S.A. Corretora De Valores'],
            ['cdgbc' => '180', 'langu' => 'PORT', 'cdgbc_desc' => 'Cm Capital Markets Corretora De Câmbio, Títulos E Valores Mobiliários Ltda'],
            ['cdgbc' => '183', 'langu' => 'PORT', 'cdgbc_desc' => 'Socred S.A. – Sociedade De Crédito Ao Microempreendedor e a Empresa De Pequeno P'],
            ['cdgbc' => '184', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Itaú BBA S.A.'],
            ['cdgbc' => '188', 'langu' => 'PORT', 'cdgbc_desc' => 'Ativa Investimentos S.A. Corretora De Títulos, Câmbio E Valores'],
            ['cdgbc' => '189', 'langu' => 'PORT', 'cdgbc_desc' => 'HS Financeira S/A Credito'],
            ['cdgbc' => '190', 'langu' => 'PORT', 'cdgbc_desc' => 'Servicoop – Cooperativa De Crédito Dos Servidores Públicos Estaduais Do Rio Gran'],
            ['cdgbc' => '191', 'langu' => 'PORT', 'cdgbc_desc' => 'Nova Futura Corretora de Títulos e Valores Mobiliários Ltda.'],
            ['cdgbc' => '194', 'langu' => 'PORT', 'cdgbc_desc' => 'Parmetal Distribuidora de Títulos e Valores Mobiliários Ltda'],
            ['cdgbc' => '196', 'langu' => 'PORT', 'cdgbc_desc' => 'Fair Corretora De Cambio S.A.'],
            ['cdgbc' => '197', 'langu' => 'PORT', 'cdgbc_desc' => 'Stone Pagamentos S.A.'],
            ['cdgbc' => '204', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Bradesco Cartões S.A.'],
            ['cdgbc' => '208', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco BTG Pactual S.A.'],
            ['cdgbc' => '212', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Original S.A.'],
            ['cdgbc' => '213', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Arbi S.A.'],
            ['cdgbc' => '217', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco John Deere S.A.'],
            ['cdgbc' => '218', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Bs2 S.A.'],
            ['cdgbc' => '222', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Crédit Agricole Brasil S.A.'],
            ['cdgbc' => '224', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Fibra S.A.'],
            ['cdgbc' => '233', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Cetelem S.A.'],
            ['cdgbc' => '237', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Bradesco S.A.'],
            ['cdgbc' => '241', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Classico S.A.'],
            ['cdgbc' => '243', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Master S.A.'],
            ['cdgbc' => '246', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Abc Brasil S.A.'],
            ['cdgbc' => '249', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Investcred Unibanco S.A.'],
            ['cdgbc' => '250', 'langu' => 'PORT', 'cdgbc_desc' => 'Bcv – Banco De Crédito E Varejo S.A.'],
            ['cdgbc' => '253', 'langu' => 'PORT', 'cdgbc_desc' => 'Bexs Corretora De Câmbio S/A'],
            ['cdgbc' => '254', 'langu' => 'PORT', 'cdgbc_desc' => 'Paraná Banco S.A.'],
            ['cdgbc' => '259', 'langu' => 'PORT', 'cdgbc_desc' => 'Moneycorp Banco De Câmbio S.A.'],
            ['cdgbc' => '260', 'langu' => 'PORT', 'cdgbc_desc' => 'Nu Pagamentos S.A.'],
            ['cdgbc' => '265', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Fator S.A.'],
            ['cdgbc' => '266', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Cedula S.A.'],
            ['cdgbc' => '268', 'langu' => 'PORT', 'cdgbc_desc' => 'Bari Companhia Hipotecária'],
            ['cdgbc' => '269', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco HSBC S.A.'],
            ['cdgbc' => '270', 'langu' => 'PORT', 'cdgbc_desc' => 'Sagitur Corretora De Câmbio Ltda.'],
            ['cdgbc' => '271', 'langu' => 'PORT', 'cdgbc_desc' => 'Ib Corretora De Câmbio, Títulos E Valores Mobiliários S.A.'],
            ['cdgbc' => '272', 'langu' => 'PORT', 'cdgbc_desc' => 'Agk Corretora De Cambio S.A.'],
            ['cdgbc' => '273', 'langu' => 'PORT', 'cdgbc_desc' => 'Cooperativa De Crédito Rural De São Miguel Do Oeste – Sulcredi/São Miguel'],
            ['cdgbc' => '274', 'langu' => 'PORT', 'cdgbc_desc' => 'Money Plus Sociedade De Crédito ao Microempreendedor e a Empresa De Pequeno Port'],
            ['cdgbc' => '276', 'langu' => 'PORT', 'cdgbc_desc' => 'Senff S.A. – Crédito'],
            ['cdgbc' => '278', 'langu' => 'PORT', 'cdgbc_desc' => 'Genial Investimentos Corretora De Valores Mobiliários S.A.'],
            ['cdgbc' => '279', 'langu' => 'PORT', 'cdgbc_desc' => 'Cooperativa De Credito Rural De Primavera Do Leste'],
            ['cdgbc' => '280', 'langu' => 'PORT', 'cdgbc_desc' => 'Avista S.A. Crédito'],
            ['cdgbc' => '281', 'langu' => 'PORT', 'cdgbc_desc' => 'Cooperativa De Crédito Rural Coopavel'],
            ['cdgbc' => '283', 'langu' => 'PORT', 'cdgbc_desc' => 'Rb Capital Investimentos Distribuidora de Títulos e Valores Mobiliários Limitada'],
            ['cdgbc' => '285', 'langu' => 'PORT', 'cdgbc_desc' => 'Frente Corretora De Câmbio Ltda.'],
            ['cdgbc' => '286', 'langu' => 'PORT', 'cdgbc_desc' => 'Cooperativa De Crédito Rural De Ouro Sulcredi/Ouro'],
            ['cdgbc' => '288', 'langu' => 'PORT', 'cdgbc_desc' => 'Carol Distribuidora De Titulos E Valores Mobiliarios Ltda.'],
            ['cdgbc' => '289', 'langu' => 'PORT', 'cdgbc_desc' => 'Decyseo Corretora De Cambio Ltda.'],
            ['cdgbc' => '290', 'langu' => 'PORT', 'cdgbc_desc' => 'Pagseguro Internet S.A.'],
            ['cdgbc' => '292', 'langu' => 'PORT', 'cdgbc_desc' => 'Bs2 Distribuidora De Títulos E Valores Mobiliários S.A.'],
            ['cdgbc' => '293', 'langu' => 'PORT', 'cdgbc_desc' => 'Lastro Rdv Distribuidora De Títulos E Valores Mobiliários Ltda.'],
            ['cdgbc' => '296', 'langu' => 'PORT', 'cdgbc_desc' => 'Vision S.A. Corretora De Cambio'],
            ['cdgbc' => '298', 'langu' => 'PORT', 'cdgbc_desc' => 'Vip’s Corretora de Câmbio Ltda.'],
            ['cdgbc' => '299', 'langu' => 'PORT', 'cdgbc_desc' => 'Sorocred Crédito'],
            ['cdgbc' => '300', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco De La Nacion Argentina'],
            ['cdgbc' => '301', 'langu' => 'PORT', 'cdgbc_desc' => 'Bpp Instituição De Pagamento S.A.'],
            ['cdgbc' => '306', 'langu' => 'PORT', 'cdgbc_desc' => 'Qi Sociedade de Crédito Direto S.A.'],
            ['cdgbc' => '309', 'langu' => 'PORT', 'cdgbc_desc' => 'Cambionet Corretora De Câmbio Ltda.'],
            ['cdgbc' => '310', 'langu' => 'PORT', 'cdgbc_desc' => 'Vortx Distribuidora de Titulos e Valores Mobiliarios Ltda.'],
            ['cdgbc' => '313', 'langu' => 'PORT', 'cdgbc_desc' => 'Amazónia Corretora De Câmbio Ltda.'],
            ['cdgbc' => '315', 'langu' => 'PORT', 'cdgbc_desc' => 'Pi Distribuidora de Títulos e Valores Mobiliários S.A.'],
            ['cdgbc' => '318', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco BMG S.A.'],
            ['cdgbc' => '319', 'langu' => 'PORT', 'cdgbc_desc' => 'Om Distribuidora de Títulos e Valores Mobiliários Ltda'],
            ['cdgbc' => '320', 'langu' => 'PORT', 'cdgbc_desc' => 'China Construction Bank (Brasil) Banco Múltiplo S.A.'],
            ['cdgbc' => '321', 'langu' => 'PORT', 'cdgbc_desc' => 'Crefaz Sociedade De Crédito Ao Microempreendedor E A Empresa De Pequeno Porte Lt'],
            ['cdgbc' => '322', 'langu' => 'PORT', 'cdgbc_desc' => 'Cooperativa De Crédito Rural De Abelardo Luz – Sulcredi/Crediluz'],
            ['cdgbc' => '323', 'langu' => 'PORT', 'cdgbc_desc' => 'Mercadopago.Com Representacoes Ltda.'],
            ['cdgbc' => '324', 'langu' => 'PORT', 'cdgbc_desc' => 'Cartos Sociedade De Crédito Direto S.A.'],
            ['cdgbc' => '325', 'langu' => 'PORT', 'cdgbc_desc' => 'Órama Distribuidora de Títulos e Valores Mobiliários S.A.'],
            ['cdgbc' => '326', 'langu' => 'PORT', 'cdgbc_desc' => 'Parati – Credito'],
            ['cdgbc' => '329', 'langu' => 'PORT', 'cdgbc_desc' => 'Qi Sociedade de Crédito Direto S.A.'],
            ['cdgbc' => '330', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Bari De Investimentos E Financiamentos S.A.'],
            ['cdgbc' => '331', 'langu' => 'PORT', 'cdgbc_desc' => 'Fram Capital Distribuidora De Títulos E Valores Mobiliários S.A.'],
            ['cdgbc' => '332', 'langu' => 'PORT', 'cdgbc_desc' => 'Acesso Soluções De Pagamento S.A.'],
            ['cdgbc' => '335', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Digio S.A.'],
            ['cdgbc' => '336', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco C6 S.A.'],
            ['cdgbc' => '340', 'langu' => 'PORT', 'cdgbc_desc' => 'Super Pagamentos e Administração de Meios Eletrônicos S.A.'],
            ['cdgbc' => '341', 'langu' => 'PORT', 'cdgbc_desc' => 'Itaú Unibanco S.A.'],
            ['cdgbc' => '342', 'langu' => 'PORT', 'cdgbc_desc' => 'Creditas Sociedade De Crédito Direto S.A.'],
            ['cdgbc' => '343', 'langu' => 'PORT', 'cdgbc_desc' => 'Ffa Sociedade De Crédito Ao Microempreendedor E À Empresa De Pequeno Porte Ltda.'],
            ['cdgbc' => '348', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Xp S.A.'],
            ['cdgbc' => '349', 'langu' => 'PORT', 'cdgbc_desc' => 'Al5 S.A. Crédito'],
            ['cdgbc' => '352', 'langu' => 'PORT', 'cdgbc_desc' => 'Toro Corretora De Títulos E Valores Mobiliários Ltda'],
            ['cdgbc' => '354', 'langu' => 'PORT', 'cdgbc_desc' => 'Necton Investimentos S.A. Corretora de Valores Mobiliários e Commodities'],
            ['cdgbc' => '355', 'langu' => 'PORT', 'cdgbc_desc' => 'Ótimo Sociedade de Crédito Direto S.A.'],
            ['cdgbc' => '362', 'langu' => 'PORT', 'cdgbc_desc' => 'Cielo S.A.'],
            ['cdgbc' => '363', 'langu' => 'PORT', 'cdgbc_desc' => 'Socopa Sociedade Corretora Paulista S.A.'],
            ['cdgbc' => '364', 'langu' => 'PORT', 'cdgbc_desc' => 'Gerencianet S.A.'],
            ['cdgbc' => '365', 'langu' => 'PORT', 'cdgbc_desc' => 'Solidus S.A. Corretora de Cambio e Valores Mobiliarios'],
            ['cdgbc' => '366', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Societe Generale Brasil S.A.'],
            ['cdgbc' => '367', 'langu' => 'PORT', 'cdgbc_desc' => 'Vitreo Distribuidora de Títulos e Valores Mobiliários S.A.'],
            ['cdgbc' => '368', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco CSF S.A.'],
            ['cdgbc' => '370', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Mizuho Do Brasil S.A.'],
            ['cdgbc' => '373', 'langu' => 'PORT', 'cdgbc_desc' => 'UP.P Sociedade de Empréstimo Entre Pessoas S.A.'],
            ['cdgbc' => '374', 'langu' => 'PORT', 'cdgbc_desc' => 'Realize Crédito'],
            ['cdgbc' => '376', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco J.P. Morgan S.A.'],
            ['cdgbc' => '378', 'langu' => 'PORT', 'cdgbc_desc' => 'Bbc Leasing S.A. – Arrendamento Mercantil'],
            ['cdgbc' => '380', 'langu' => 'PORT', 'cdgbc_desc' => 'Picpay Servicos S.A.'],
            ['cdgbc' => '381', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Mercedes-Benz Do Brasil S.A.'],
            ['cdgbc' => '384', 'langu' => 'PORT', 'cdgbc_desc' => 'Global Financas – Sociedade De Credito Ao Microempreendedor E A Empresa De Pequeno Porte Ltda'],
            ['cdgbc' => '387', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Toyota Do Brasil S.A.'],
            ['cdgbc' => '389', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Mercantil do Brasil S.A.'],
            ['cdgbc' => '390', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Gm S.A.'],
            ['cdgbc' => '391', 'langu' => 'PORT', 'cdgbc_desc' => 'Cooperativa De Credito Rural De Ibiam – Sulcredi/Ibiam'],
            ['cdgbc' => '393', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Volkswagen S.A.'],
            ['cdgbc' => '394', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Bradesco Financiamentos S.A.'],
            ['cdgbc' => '396', 'langu' => 'PORT', 'cdgbc_desc' => 'Hub Pagamentos S.A'],
            ['cdgbc' => '397', 'langu' => 'PORT', 'cdgbc_desc' => 'Listo Sociedade De Credito Direto S.A.'],
            ['cdgbc' => '399', 'langu' => 'PORT', 'cdgbc_desc' => 'Kirton Bank S.A. – Banco Múltiplo'],
            ['cdgbc' => '403', 'langu' => 'PORT', 'cdgbc_desc' => 'Cora Sociedade De Crédito Direto S.A.'],
            ['cdgbc' => '404', 'langu' => 'PORT', 'cdgbc_desc' => 'Sumup Sociedade De Crédito Direto S.A.'],
            ['cdgbc' => '408', 'langu' => 'PORT', 'cdgbc_desc' => 'Bónuscred Sociedade De Crédito Direto S.A.'],
            ['cdgbc' => '412', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Capital S.A.'],
            ['cdgbc' => '422', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Safra S.A.'],
            ['cdgbc' => '456', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Mufg Brasil S.A.'],
            ['cdgbc' => '464', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Sumitomo Mitsui Brasileiro S.A.'],
            ['cdgbc' => '473', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Caixa Geral – Brasil S.A.'],
            ['cdgbc' => '477', 'langu' => 'PORT', 'cdgbc_desc' => 'Citibank N.A.'],
            ['cdgbc' => '479', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Itaubank S.A.'],
            ['cdgbc' => '487', 'langu' => 'PORT', 'cdgbc_desc' => 'Deutsche Bank S.A. – Banco Alemao'],
            ['cdgbc' => '488', 'langu' => 'PORT', 'cdgbc_desc' => 'Jpmorgan Chase Bank'],
            ['cdgbc' => '492', 'langu' => 'PORT', 'cdgbc_desc' => 'Ing Bank N.V.'],
            ['cdgbc' => '494', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco de La Republica Oriental del Uruguay'],
            ['cdgbc' => '495', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco De La Provincia De Buenos Aires'],
            ['cdgbc' => '505', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Credit Suisse (Brasil) S.A.'],
            ['cdgbc' => '545', 'langu' => 'PORT', 'cdgbc_desc' => 'Senso Corretora De Cambio E Valores Mobiliarios S.A'],
            ['cdgbc' => '600', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Luso Brasileiro S.A.'],
            ['cdgbc' => '604', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Industrial Do Brasil S.A.'],
            ['cdgbc' => '610', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Vr S.A.'],
            ['cdgbc' => '611', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Paulista S.A.'],
            ['cdgbc' => '612', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Guanabara S.A.'],
            ['cdgbc' => '613', 'langu' => 'PORT', 'cdgbc_desc' => 'Omni Banco S.A.'],
            ['cdgbc' => '623', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Pan S.A.'],
            ['cdgbc' => '626', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco C6 Consignado S.A.'],
            ['cdgbc' => '630', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Smartbank S.A.'],
            ['cdgbc' => '633', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Rendimento S.A.'],
            ['cdgbc' => '634', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Triangulo S.A.'],
            ['cdgbc' => '637', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Sofisa S.A.'],
            ['cdgbc' => '641', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Alvorada S.A.'],
            ['cdgbc' => '643', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Pine S.A.'],
            ['cdgbc' => '652', 'langu' => 'PORT', 'cdgbc_desc' => 'Itaú Unibanco Holding S.A.'],
            ['cdgbc' => '653', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Indusval S.A.'],
            ['cdgbc' => '654', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Digimais S.A.'],
            ['cdgbc' => '655', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Votorantim S.A.'],
            ['cdgbc' => '707', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Daycoval S.A.'],
            ['cdgbc' => '712', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Ourinvest S.A.'],
            ['cdgbc' => '720', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco RNX'],
            ['cdgbc' => '735', 'langu' => 'PORT', 'cdgbc_desc' => 'Neon Pagamentos'],
            ['cdgbc' => '739', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Cetelem S.A.'],
            ['cdgbc' => '741', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Ribeirao Preto S.A.'],
            ['cdgbc' => '743', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Semear S.A.'],
            ['cdgbc' => '745', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Citibank S.A.'],
            ['cdgbc' => '746', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Modal S.A.'],
            ['cdgbc' => '747', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Rabobank International Brasil S.A.'],
            ['cdgbc' => '748', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Cooperativo Sicredi S.A.'],
            ['cdgbc' => '751', 'langu' => 'PORT', 'cdgbc_desc' => 'Scotiabank Brasil S.A. Banco Múltiplo'],
            ['cdgbc' => '752', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Bnp Paribas Brasil S.A.'],
            ['cdgbc' => '753', 'langu' => 'PORT', 'cdgbc_desc' => 'Novo Banco Continental S.A. – Banco Múltiplo'],
            ['cdgbc' => '754', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Sistema S.A.'],
            ['cdgbc' => '755', 'langu' => 'PORT', 'cdgbc_desc' => 'Bank of America Merrill Lynch Banco Múltiplo S.A.'],
            ['cdgbc' => '756', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Cooperativo Do Brasil S.A. – Bancoob – Sicoob'],
            ['cdgbc' => '757', 'langu' => 'PORT', 'cdgbc_desc' => 'Banco Keb Hana Do Brasil S.A.'],
        ];
        DB::table('tbdm_bnccode')->insert($bnccode);

        $tpplanovd = [
            ['tp_plano' => 'INICI', 'langu' => 'PORT', 'tp_plano_desc' => 'Inicial'],
            ['tp_plano' => 'INTER', 'langu' => 'PORT', 'tp_plano_desc' => 'Intermediário'],
            ['tp_plano' => 'COMP', 'langu' => 'PORT', 'tp_plano_desc' => 'Completo'],
            ['tp_plano' => 'BOLT', 'langu' => 'PORT', 'tp_plano_desc' => 'Boletagem'],
        ];

        DB::table('tbdm_tpplanovd')->insert($tpplanovd);

        $estados = [
            ['langu' => 'PORT', 'estado' => 'AC', 'estado_pais' => 'BR', 'estado_desc' => 'ACRE'],
            ['langu' => 'PORT', 'estado' => 'AL', 'estado_pais' => 'BR', 'estado_desc' => 'ALAGOAS'],
            ['langu' => 'PORT', 'estado' => 'AM', 'estado_pais' => 'BR', 'estado_desc' => 'AMAZONAS'],
            ['langu' => 'PORT', 'estado' => 'AP', 'estado_pais' => 'BR', 'estado_desc' => 'AMAPA'],
            ['langu' => 'PORT', 'estado' => 'BA', 'estado_pais' => 'BR', 'estado_desc' => 'BAHIA'],
            ['langu' => 'PORT', 'estado' => 'CE', 'estado_pais' => 'BR', 'estado_desc' => 'CEARÁ'],
            ['langu' => 'PORT', 'estado' => 'DF', 'estado_pais' => 'BR', 'estado_desc' => 'DISTRITO FEDERAL'],
            ['langu' => 'PORT', 'estado' => 'ES', 'estado_pais' => 'BR', 'estado_desc' => 'ESPIRITO SANTO'],
            ['langu' => 'PORT', 'estado' => 'GO', 'estado_pais' => 'BR', 'estado_desc' => 'GOIAS'],
            ['langu' => 'PORT', 'estado' => 'MA', 'estado_pais' => 'BR', 'estado_desc' => 'MARANHAO'],
            ['langu' => 'PORT', 'estado' => 'MG', 'estado_pais' => 'BR', 'estado_desc' => 'MINAS GERAIS'],
            ['langu' => 'PORT', 'estado' => 'MS', 'estado_pais' => 'BR', 'estado_desc' => 'MATO GROSSO SUL'],
            ['langu' => 'PORT', 'estado' => 'MT', 'estado_pais' => 'BR', 'estado_desc' => 'MATO GROSSO'],
            ['langu' => 'PORT', 'estado' => 'PA', 'estado_pais' => 'BR', 'estado_desc' => 'PARA'],
            ['langu' => 'PORT', 'estado' => 'PB', 'estado_pais' => 'BR', 'estado_desc' => 'PARAIBA'],
            ['langu' => 'PORT', 'estado' => 'PE', 'estado_pais' => 'BR', 'estado_desc' => 'PERNAMBUCO'],
            ['langu' => 'PORT', 'estado' => 'PI', 'estado_pais' => 'BR', 'estado_desc' => 'PIAUI'],
            ['langu' => 'PORT', 'estado' => 'PR', 'estado_pais' => 'BR', 'estado_desc' => 'PARANA'],
            ['langu' => 'PORT', 'estado' => 'RJ', 'estado_pais' => 'BR', 'estado_desc' => 'RIO DE JANEIRO'],
            ['langu' => 'PORT', 'estado' => 'RN', 'estado_pais' => 'BR', 'estado_desc' => 'RIO GRANDE DO NORTE'],
            ['langu' => 'PORT', 'estado' => 'RO', 'estado_pais' => 'BR', 'estado_desc' => 'RONDONIA'],
            ['langu' => 'PORT', 'estado' => 'RR', 'estado_pais' => 'BR', 'estado_desc' => 'RORAIMA'],
            ['langu' => 'PORT', 'estado' => 'RS', 'estado_pais' => 'BR', 'estado_desc' => 'RIO GRANDE SO SUL'],
            ['langu' => 'PORT', 'estado' => 'SC', 'estado_pais' => 'BR', 'estado_desc' => 'SANTA CATARINA'],
            ['langu' => 'PORT', 'estado' => 'SE', 'estado_pais' => 'BR', 'estado_desc' => 'SERGIPE'],
            ['langu' => 'PORT', 'estado' => 'SP', 'estado_pais' => 'BR', 'estado_desc' => 'SAO PAULO'],
            ['langu' => 'PORT', 'estado' => 'TO', 'estado_pais' => 'BR', 'estado_desc' => 'TOCANTINS']
        ];

        DB::table('tbdm_estados')->insert($estados);

        $pais = [
            ['pais' => 'BR', 'langu' => 'PORT', 'pais_desc' => 'Brasil'],
        ];

        DB::table('tbdm_pais')->insert($pais);

        $cliente_tp = [
            ['cliente_tipo' => '1', 'langu' => 'PORT', 'cliente_tipo_desc' => 'Física'],
            ['cliente_tipo' => '2', 'langu' => 'PORT', 'cliente_tipo_desc' => 'Jurídica'],
            ['cliente_tipo' => '3', 'langu' => 'PORT', 'cliente_tipo_desc' => 'Governamental'],
            ['cliente_tipo' => '4', 'langu' => 'PORT', 'cliente_tipo_desc' => 'ONG'],
        ];

        DB::table('tbdm_cliente_tp')->insert($cliente_tp);

        $cliente_sts = [
            ['cliente_sts' => 'AT', 'langu' => 'PORT', 'cliente_sts_desc' => 'Ativo'],
            ['cliente_sts' => 'IN', 'langu' => 'PORT', 'cliente_sts_desc' => 'Inativo'],
            ['cliente_sts' => 'EX', 'langu' => 'PORT', 'cliente_sts_desc' => 'Excluído'],
            ['cliente_sts' => 'BL', 'langu' => 'PORT', 'cliente_sts_desc' => 'Bloqueado'],
            ['cliente_sts' => 'NA', 'langu' => 'PORT', 'cliente_sts_desc' => 'Em Análise'],
            ['cliente_sts' => 'ID', 'langu' => 'PORT', 'cliente_sts_desc' => 'Inadimplente'],
            ['cliente_sts' => 'MN', 'langu' => 'PORT', 'cliente_sts_desc' => 'Monitorado'],
        ];

        DB::table('tbdm_cliente_sts')->insert($cliente_sts);

        $card_tp = [
            ['card_tp' => 'PRE', 'langu' => 'PORT', 'card_tp_desc' => 'Pré-Pago'],
            ['card_tp' => 'POS', 'langu' => 'PORT', 'card_tp_desc' => 'Pós-Pago'],
        ];

        DB::table('tbdm_card_tp')->insert($card_tp);

        $card_mod = [
            ['card_mod' => 'CRDT', 'langu' => 'PORT', 'card_mod_desc' => 'Crédito'],
            ['card_mod' => 'GIFT', 'langu' => 'PORT', 'card_mod_desc' => 'Gift Card'],
            ['card_mod' => 'FIDL', 'langu' => 'PORT', 'card_mod_desc' => 'Fidelidade'],
        ];

        DB::table('tbdm_card_mod')->insert($card_mod);

        $card_categ = [
            ['card_categ' => 'OURO', 'langu' => 'PORT', 'card_categ_desc' => 'Ouro'],
            ['card_categ' => 'PRTA', 'langu' => 'PORT', 'card_categ_desc' => 'Prata'],
            ['card_categ' => 'BRNZ', 'langu' => 'PORT', 'card_categ_desc' => 'Bronze'],
            ['card_categ' => 'BLCK', 'langu' => 'PORT', 'card_categ_desc' => 'Black'],
        ];

        DB::table('tbdm_card_categ')->insert($card_categ);

        $card_sts = [
            ['card_sts' => 'AT', 'langu' => 'PORT', 'card_sts_desc' => 'Ativo'],
            ['card_sts' => 'IN', 'langu' => 'PORT', 'card_sts_desc' => 'Inativo'],
            ['card_sts' => 'EX', 'langu' => 'PORT', 'card_sts_desc' => 'Excluído'],
            ['card_sts' => 'BL', 'langu' => 'PORT', 'card_sts_desc' => 'Bloqueado'],
        ];

        DB::table('tbdm_card_sts')->insert($card_sts);

        $prgpts_sts = [
            ['prgpts_sts' => 'AT', 'langu' => 'PORT', 'prgpts_sts_desc' => 'Ativo'],
            ['prgpts_sts' => 'IN', 'langu' => 'PORT', 'prgpts_sts_desc' => 'Inativo'],
            ['prgpts_sts' => 'EX', 'langu' => 'PORT', 'prgpts_sts_desc' => 'Excluído'],
            ['prgpts_sts' => 'BL', 'langu' => 'PORT', 'prgpts_sts_desc' => 'Bloqueado'],
        ];

        DB::table('tbdm_prgpts_sts')->insert($prgpts_sts);

        $meiocom = [
            ['emp_meiocom' => 'GG', 'langu' => 'PORT', 'meio_com_desc' => 'Google'],
            ['emp_meiocom' => 'FC', 'langu' => 'PORT', 'meio_com_desc' => 'Facebook'],
            ['emp_meiocom' => 'IN', 'langu' => 'PORT', 'meio_com_desc' => 'Instagram'],
            ['emp_meiocom' => 'EM', 'langu' => 'PORT', 'meio_com_desc' => 'Email Marketing'],
            ['emp_meiocom' => 'ID', 'langu' => 'PORT', 'meio_com_desc' => 'Indicação'],
            ['emp_meiocom' => 'EV', 'langu' => 'PORT', 'meio_com_desc' => 'Evento'],
        ];

        DB::table('tbdm_meiocom')->insert($meiocom);

        $produto_tp = [
            ['produto_tipo' => '1', 'langu' => 'PORT', 'produto_tipo_desc' => 'Produto'],
            ['produto_tipo' => '2', 'langu' => 'PORT', 'produto_tipo_desc' => 'Serviço'],
            ['produto_tipo' => '3', 'langu' => 'PORT', 'produto_tipo_desc' => 'Participante'],
        ];

        DB::table('tbdm_produto_tp')->insert($produto_tp);

        $produto_sts = [
            ['produto_sts' => 'AT', 'langu' => 'PORT', 'produto_sts_desc' => 'Ativo'],
            ['produto_sts' => 'IN', 'langu' => 'PORT', 'produto_sts_desc' => 'Inativo'],
            ['produto_sts' => 'EX', 'langu' => 'PORT', 'produto_sts_desc' => 'Excluído'],
            ['produto_sts' => 'BL', 'langu' => 'PORT', 'produto_sts_desc' => 'Bloqueado'],
        ];

        DB::table('tbdm_produto_sts')->insert($produto_sts);

        $adquirentes = [
            ['emp_adqrnt' => 'AFINZ', 'adqrnt_desc' => 'Afinz'],
            ['emp_adqrnt' => 'DOCK', 'adqrnt_desc' => 'Dock'],
        ];

        DB::table('tbdm_adquirentes')->insert($adquirentes);

        $tpbolet = [
            ['emp_tpbolet' => 'BTS', 'langu' => 'PORT', 'tpbolet_desc' => 'Boletagem Simples'],
            ['emp_tpbolet' => 'BTP', 'langu' => 'PORT', 'tpbolet_desc' => 'Boletagem + PIX'],
            ['emp_tpbolet' => 'BTC', 'langu' => 'PORT', 'tpbolet_desc' => 'Boletagem + Cobrança'],
        ];

        DB::table('tbdm_tpbolet')->insert($tpbolet);

        $fornec = [
            ['fornec' => 'K8', 'langu' => 'PORT', 'fornec_desc' => 'K8'],
            ['fornec' => 'ARBI', 'langu' => 'PORT', 'fornec_desc' => 'ARBI'],
            ['fornec' => 'DGO', 'langu' => 'PORT', 'fornec_desc' => 'Digital Ocean'],
            ['fornec' => 'AWS', 'langu' => 'PORT', 'fornec_desc' => 'AWS'],
            ['fornec' => 'D4S', 'langu' => 'PORT', 'fornec_desc' => 'D4Sign'],
            ['fornec' => 'GLG', 'langu' => 'PORT', 'fornec_desc' => 'Google'],
            ['fornec' => 'LCW', 'langu' => 'PORT', 'fornec_desc' => 'Locaweb'],
            ['fornec' => 'OFC', 'langu' => 'PORT', 'fornec_desc' => 'Office'],
        ];

        DB::table('tbdm_fornec')->insert($fornec);

        $tbdm_destvlr = [
            ['langu' => 'PORT', "destvlr" => "WLTM", "destvlr_desc" => "Wallet - Multban"],
            ['langu' => 'PORT', "destvlr" => "CTBA", "destvlr_desc" => "Conta Bancária - Arbi"],
            ['langu' => 'PORT', "destvlr" => "CTBS", "destvlr_desc" => "Conta Bancária - Secundária"],
        ];

        DB::table('tbdm_destvlr')->insert($tbdm_destvlr);

        $tbdm_tax_categ = [
            ['langu' => 'PORT', "tax_categ" => "PVST", "tax_categ_desc" => "Primeira à Vista"],
            ['langu' => 'PORT', "tax_categ" => "P30D", "tax_categ_desc" => "Primeira para 30 Dias"],
            ['langu' => 'PORT', "tax_categ" => "P60D", "tax_categ_desc" => "Primeira para 60 Dias"],
            ['langu' => 'PORT', "tax_categ" => "P90D", "tax_categ_desc" => "Primeira para 90 Dias"],
        ];

        DB::table('tbdm_tax_categ')->insert($tbdm_tax_categ);

        $tbdm_msg_categ = [
            ['langu' => 'PORT', "msg_categ" => "CTRMT", "msg_categ_desc" => "Contrato Mult+"],
            ['langu' => 'PORT', "msg_categ" => "VLDCD", "msg_categ_desc" => "Validação de Cadastro"],
            ['langu' => 'PORT', "msg_categ" => "CRSEN", "msg_categ_desc" => "Criação de Senha"],
            ['langu' => 'PORT', "msg_categ" => "CMTPG", "msg_categ_desc" => "Comunicado de Título Pago"],
            ['langu' => 'PORT', "msg_categ" => "CMTAV", "msg_categ_desc" => "Comunicado de Título à Vencer"],
            ['langu' => 'PORT', "msg_categ" => "CMTVC", "msg_categ_desc" => "Comunicado de Título Vencido"],
            ['langu' => 'PORT', "msg_categ" => "CBIN1", "msg_categ_desc" => "Cobrança de Inadimplente N1"],
            ['langu' => 'PORT', "msg_categ" => "CBIN2", "msg_categ_desc" => "Cobrança de Inadimplente N2"],
            ['langu' => 'PORT', "msg_categ" => "CBIN3", "msg_categ_desc" => "Cobrança de Inadimplente N3"],
            ['langu' => 'PORT', "msg_categ" => "CBCPR", "msg_categ_desc" => "Cabeçalho do Comprovante"],
            ['langu' => 'PORT', "msg_categ" => "MULTB", "msg_categ_desc" => "Dados da Multban"],
            ['langu' => 'PORT', "msg_categ" => "RPCPR", "msg_categ_desc" => "Roda Pé do Comprovante"],
            ['langu' => 'PORT', "msg_categ" => "AUTHO", "msg_categ_desc" => "Autorização de Transação"],
        ];

        DB::table('tbdm_msg_categ')->insert($tbdm_msg_categ);

        $tbdm_canal_cm = [
            ['langu' => 'PORT', "canal_id" => "1", "canal_desc" => "E-mail"],
            ['langu' => 'PORT', "canal_id" => "2", "canal_desc" => "SMS"],
            ['langu' => 'PORT', "canal_id" => "3", "canal_desc" => "Whats App"],
            ['langu' => 'PORT', "canal_id" => "4", "canal_desc" => "Comprovante de Pagamento"],
        ];

        DB::table('tbdm_canal_cm')->insert($tbdm_canal_cm);

        $tbcf_msg_comp = [
            ['emp_id' => 1, 'langu' => 'PORT', "canal_id" => "4", "msg_categ" => "CBCPR", 'msg_text' => "BANCO ARBI – S/A \n INSTITUICAO FINANCEIRA - REG. BACEN 54403563 \n CNPJ: 54.403.563/0001-50"],
            ['emp_id' => 1, 'langu' => 'PORT', "canal_id" => "4", "msg_categ" => "MULTB", 'msg_text' => "MULTBAN\n SISTEMA DE PAGAMENTOS INTELIGENTES LTDA\n CNPJ: 01.179.943/0001-96"],
            ['emp_id' => 1, 'langu' => 'PORT', "canal_id" => "4", "msg_categ" => "RPCPR", 'msg_text' => "RECONHEÇO QUE PAGUEI A IMPORTANCIA ACIMA"],
            ['emp_id' => 1, 'langu' => 'PORT', "canal_id" => "4", "msg_categ" => "AUTHO", 'msg_text' => "ESTA TRANSAÇÃO FOI PROCESSADA EM AMBIENTE SEGURO E AUDITADO, EM CONFORMIDADE COM PADRÕES DE SEGURANÇA E AUDITORIA DO SETOR DE MEIOS DE PAGAMENTO"],
        ];

        DB::table('tbcf_msg_comp')->insert($tbcf_msg_comp);

        $tbdm_api_grupo = [
            ['langu' => 'PORT', "api_grupo" => "BCO", "api_grupo_desc" => "Bancária"],
            ['langu' => 'PORT', "api_grupo" => "SCR", "api_grupo_desc" => "SCORE"],
            ['langu' => 'PORT', "api_grupo" => "PRT", "api_grupo_desc" => "Protestos"],
        ];

        DB::table('tbdm_api_grupo')->insert($tbdm_api_grupo);

        $tbdm_api_subgrp = [
            ['langu' => 'PORT', "api_subgrp" => "RGBLT", "api_subgrp_desc" => "Registro Boleto"],
            ['langu' => 'PORT', "api_subgrp" => "RGPIX", "api_subgrp_desc" => "Registro PIX"],
            ['langu' => 'PORT', "api_subgrp" => "BXBLT", "api_subgrp_desc" => "Baixa Boleto"],
            ['langu' => 'PORT', "api_subgrp" => "BXPIX", "api_subgrp_desc" => "Baixa PIX"],
        ];

        DB::table('tbdm_api_subgrp')->insert($tbdm_api_subgrp);

        $tbdm_meio_pag = [
            ['meio_order' => 1, 'langu' => 'PORT', "meio_pag" => "DN", "meio_pag_icon" => "dinheiro.svg", "meio_pag_desc" => "Dinheiro"],
            ['meio_order' => 2, 'langu' => 'PORT', "meio_pag" => "PX", "meio_pag_icon" => "pix.svg", "meio_pag_desc" => "Pix"],
            ['meio_order' => 3, 'langu' => 'PORT', "meio_pag" => "BL", "meio_pag_icon" => "boleto.svg", "meio_pag_desc" => "Boleto"],
            ['meio_order' => 4, 'langu' => 'PORT', "meio_pag" => "CM", "meio_pag_icon" => "card-mult.svg", "meio_pag_desc" => "Cartão MULT"],
            ['meio_order' => 5, 'langu' => 'PORT', "meio_pag" => "OT", "meio_pag_icon" => "outros.svg", "meio_pag_desc" => "Outros"],
        ];

        DB::table('tbdm_meio_pag')->insert($tbdm_meio_pag);

        $tbdm_agendamento_tp = [
            ['langu' => 'PORT', "agendamento_tipo" => "1", "agendamento_tipo_desc" => "Consulta"],
            ['langu' => 'PORT', "agendamento_tipo" => "2", "agendamento_tipo_desc" => "Exame"],
            ['langu' => 'PORT', "agendamento_tipo" => "3", "agendamento_tipo_desc" => "Retorno"],
            ['langu' => 'PORT', "agendamento_tipo" => "4", "agendamento_tipo_desc" => "Urgência"],
        ];

        DB::table('tbdm_agendamento_tp')->insert($tbdm_agendamento_tp);

        $tbdm_agendamento_sts = [
            ["langu" => "PORT", "agendamento_sts" => "AG", "agendamento_sts_desc" => "Agendado"],
            ["langu" => "PORT", "agendamento_sts" => "CN", "agendamento_sts_desc" => "Cancelado"],
            ["langu" => "PORT", "agendamento_sts" => "RE", "agendamento_sts_desc" => "Realizado"],
            ["langu" => "PORT", "agendamento_sts" => "NA", "agendamento_sts_desc" => "Não Compareceu"],
        ];

        DB::table('tbdm_agendamento_sts')->insert($tbdm_agendamento_sts);

        $tbdm_cnd_pag = [
            ['langu' => 'PORT', "cnd_pag" => "1", "cnd_pag_desc" => "À Vista"],
            ['langu' => 'PORT', "cnd_pag" => "2", "cnd_pag_desc" => "Parcelado"],
        ];

        DB::table('tbdm_cnd_pag')->insert($tbdm_cnd_pag);

        $tbdm_parcela_sts = [
            ['langu' => 'PORT', "parcela_sts" => "BXD", "parcela_sts_desc" => "BAIXADO"],
            ['langu' => 'PORT', "parcela_sts" => "BXI", "parcela_sts_desc" => "BAIXADO - INADIMPLENTE"],
            ['langu' => 'PORT', "parcela_sts" => "REG", "parcela_sts_desc" => "REGISTRADO"],
            ['langu' => 'PORT', "parcela_sts" => "IND", "parcela_sts_desc" => "INADIMPLENTE"],
        ];

        DB::table('tbdm_parcela_sts')->insert($tbdm_parcela_sts);

        $tbdm_lanc_tp = [
            ['langu' => 'PORT', "lanc_tp" => "VLR_CMIS", "lanc_tp_desc" => "Comissão Paga para Vendedores e Representantes"],
            ['langu' => 'PORT', "lanc_tp" => "DIV_JURS", "lanc_tp_desc" => "Divisão dos Juros das Vendas Parceladas"],
            ['langu' => 'PORT', "lanc_tp" => "DIV_MTJR", "lanc_tp_desc" => "Divisão Multa e Juros por Atraso"],
            ['langu' => 'PORT', "lanc_tp" => "QTD_PNTS", "lanc_tp_desc" => "Pontos Utilizados para Liquidação da Venda"],
            ['langu' => 'PORT', "lanc_tp" => "VLR_REBT", "lanc_tp_desc" => "Rebate pago para Parceiros"],
            ['langu' => 'PORT', "lanc_tp" => "VLR_VNDA", "lanc_tp_desc" => "Valor da venda referente ao Estabelecimento"],
            ['langu' => 'PORT', "lanc_tp" => "DINHEIRO", "lanc_tp_desc" => "Recebimento em Espécie"],
            ['langu' => 'PORT', "lanc_tp" => "VLR_ANTE", "lanc_tp_desc" => "Valores Antecipados"],
            ['langu' => 'PORT', "lanc_tp" => "TAXA_ADM", "lanc_tp_desc" => "Valor da venda referente a Taxa Administrativa"],
            ['langu' => 'PORT', "lanc_tp" => "TAXA_ANT", "lanc_tp_desc" => "Valor da Taxa de Antecipação"],
            ['langu' => 'PORT', "lanc_tp" => "TAXA_BAC", "lanc_tp_desc" => "Valor referente a taxa do Banco Central"],
            ['langu' => 'PORT', "lanc_tp" => "VLR_ROTS", "lanc_tp_desc" => "Royalties pago para Tercerios"],
        ];

        DB::table('tbdm_lanc_tp')->insert($tbdm_lanc_tp);

        $tbdm_fatura_sts = [
            ['langu' => 'PORT', "fatura_sts" => "1", "fatura_sts_desc" => "ABERTA"],
            ['langu' => 'PORT', "fatura_sts" => "2", "fatura_sts_desc" => "FECHADA"],
        ];

        DB::table('tbdm_fatura_sts')->insert($tbdm_fatura_sts);

        $tbdm_regra_parc = [
            ['langu' => 'PORT', "opcao_parc" => "1", "meio_pag" => "BL", "opcao_parc_desc" => "À Vista", "tax_categ" => "PVST", "regra_parc" => "5"],
            ['langu' => 'PORT', "opcao_parc" => "2", "meio_pag" => "BL", "opcao_parc_desc" => "30 dias", "tax_categ" => "P30D", "regra_parc" => "30"],
            ['langu' => 'PORT', "opcao_parc" => "3", "meio_pag" => "BL", "opcao_parc_desc" => "60 dias", "tax_categ" => "P60D", "regra_parc" => "60"],
            ['langu' => 'PORT', "opcao_parc" => "4", "meio_pag" => "BL", "opcao_parc_desc" => "90 dias", "tax_categ" => "P90D", "regra_parc" => "90"],
            ['langu' => 'PORT', "opcao_parc" => "5", "meio_pag" => "BL", "opcao_parc_desc" => "Personalizado", "tax_categ" => NULL, "regra_parc" => NULL],
            ['langu' => 'PORT', "opcao_parc" => "6", "meio_pag" => "CM", "opcao_parc_desc" => "Rotativo", "tax_categ" => "P30D", "regra_parc" => NULL],
            ['langu' => 'PORT', "opcao_parc" => "7", "meio_pag" => "CM", "opcao_parc_desc" => "30 dias", "tax_categ" => "P30D", "regra_parc" => "30"],
            ['langu' => 'PORT', "opcao_parc" => "8", "meio_pag" => "CM", "opcao_parc_desc" => "60 dias", "tax_categ" => "P60D", "regra_parc" => "60"],
            ['langu' => 'PORT', "opcao_parc" => "9", "meio_pag" => "CM", "opcao_parc_desc" => "90 dias", "tax_categ" => "P90D", "regra_parc" => "90"],
        ];

        DB::table('tbdm_regra_parc')->insert($tbdm_regra_parc);

        $tbdm_convenios = [

            ["convenio_desc" => "Alice Saúde"],
            ["convenio_desc" => "Allianz Saúde"],
            ["convenio_desc" => "Ameplan Saúde"],
            ["convenio_desc" => "Amil"],
            ["convenio_desc" => "Ampla Saúde"],
            ["convenio_desc" => "Ana Costa Saúde"],
            ["convenio_desc" => "Ativia Saúde"],
            ["convenio_desc" => "Biosaúde"],
            ["convenio_desc" => "Biovida Saúde"],
            ["convenio_desc" => "Blue Med Saúde"],
            ["convenio_desc" => "Bradesco Saúde"],
            ["convenio_desc" => "Caixa Saúde"],
            ["convenio_desc" => "Care Plus"],
            ["convenio_desc" => "Classes Laboriosas"],
            ["convenio_desc" => "Cruz Azul Saúde"],
            ["convenio_desc" => "Cuidar.Me"],
            ["convenio_desc" => "Garantia de Saúde"],
            ["convenio_desc" => "Go Care Saúde"],
            ["convenio_desc" => "Golden Cross"],
            ["convenio_desc" => "Greenline Saúde"],
            ["convenio_desc" => "Hapvida"],
            ["convenio_desc" => "Hbc Saúde"],
            ["convenio_desc" => "Health Santaris"],
            ["convenio_desc" => "Interclinicas"],
            ["convenio_desc" => "Medical Health"],
            ["convenio_desc" => "Medsenior Saúde"],
            ["convenio_desc" => "Med Tour Saúde"],
            ["convenio_desc" => "Notre Dame Intermédica"],
            ["convenio_desc" => "One Health"],
            ["convenio_desc" => "Plansaúde"],
            ["convenio_desc" => "Plena Saúde"],
            ["convenio_desc" => "Porto Seguro Saúde"],
            ["convenio_desc" => "Prevent Senior"],
            ["convenio_desc" => "QSaúde"],
            ["convenio_desc" => "Sagrada Familia Saúde"],
            ["convenio_desc" => "Sami Saúde"],
            ["convenio_desc" => "Santa Casa de Maua"],
            ["convenio_desc" => "Santa Helena Saúde"],
            ["convenio_desc" => "Santa Saúde"],
            ["convenio_desc" => "São Camilo Saúde"],
            ["convenio_desc" => "São Cristóvão Saúde"],
        ];

        DB::table('tbdm_convenios')->insert($tbdm_convenios);

        $tbdm_produtos_geral = Produto::insert([
            ## PRODUTO 1
            [
                'emp_id' => 1,
                'produto_id' => 1,
                'produto_sts' => 'AT',
                'produto_tipo' => 1,
                'partcp_pvlaor' => NULL,
                'partcp_empid' => NULL,
                'partcp_seller' => NULL,
                'partcp_pgsplit' => NULL,
                'partcp_pgtransf' => NULL,
                'partcp_cdgbc' => NULL,
                'partcp_agbc' => NULL,
                'partcp_ccbc' => NULL,
                'partcp_pix' => NULL,
                'produto_ncm' => 65489,
                'produto_cdgb' => 744654,
                'produto_peso' => 1.30,
                'produto_ctrl' => 'X',
                'produto_dc' => 'Produto Teste C',
                'produto_dm' => 'Produto Teste M',
                'produto_dl' => 'Produto Teste L',
                'produto_dt' => 'Produto Teste T',
                'produto_vlr' => 130.00,
                'criador' => 1,
                'dthr_cr' => '2025-05-28 21:17:07',
                'modificador' => 1,
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            ## PRODUTO 2
            [
                'emp_id' => 1,
                'produto_id' => 2,
                'produto_sts' => 'AT',
                'produto_tipo' => 2,
                'partcp_pvlaor' => NULL,
                'partcp_empid' => NULL,
                'partcp_seller' => NULL,
                'partcp_pgsplit' => NULL,
                'partcp_pgtransf' => NULL,
                'partcp_cdgbc' => NULL,
                'partcp_agbc' => NULL,
                'partcp_ccbc' => NULL,
                'partcp_pix' => NULL,
                'produto_ncm' => NULL,
                'produto_cdgb' => NULL,
                'produto_peso' => NULL,
                'produto_ctrl' => NULL,
                'produto_dc' => 'Teste Serviço C',
                'produto_dm' => 'Teste Serviço M',
                'produto_dl' => 'Teste Serviço L',
                'produto_dt' => 'Teste Serviço T',
                'produto_vlr' => 150.00,
                'criador' => 1,
                'dthr_cr' => '2025-05-28 21:17:07',
                'modificador' => 1,
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            ## PRODUTO 3
            [
                'emp_id' => 1,
                'produto_id' => 3,
                'produto_sts' => 'AT',
                'produto_tipo' => 3,
                'partcp_pvlaor' => 100,
                'partcp_empid' => 1,
                'partcp_seller' => 654674985,
                'partcp_pgsplit' => 'X',
                'partcp_pgtransf' => NULL,
                'partcp_cdgbc' => NULL,
                'partcp_agbc' => NULL,
                'partcp_ccbc' => NULL,
                'partcp_pix' => NULL,
                'produto_ncm' => NULL,
                'produto_cdgb' => NULL,
                'produto_peso' => NULL,
                'produto_ctrl' => NULL,
                'produto_dc' => 'Teste Partic C',
                'produto_dm' => 'Teste Partic M',
                'produto_dl' => 'Teste Partic L',
                'produto_dt' => 'Teste Partic T',
                'produto_vlr' => 250.00,
                'criador' => 1,
                'dthr_cr' => '2025-05-28 21:17:07',
                'modificador' => 1,
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            ## PRODUTO 4
            [
                'emp_id' => 1,
                'produto_id' => 4,
                'produto_sts' => 'AT',
                'produto_tipo' => 2,
                'partcp_pvlaor' => NULL,
                'partcp_empid' => NULL,
                'partcp_seller' => NULL,
                'partcp_pgsplit' => NULL,
                'partcp_pgtransf' => NULL,
                'partcp_cdgbc' => NULL,
                'partcp_agbc' => NULL,
                'partcp_ccbc' => NULL,
                'partcp_pix' => NULL,
                'produto_ncm' => NULL,
                'produto_cdgb' => NULL,
                'produto_peso' => NULL,
                'produto_ctrl' => NULL,
                'produto_dc' => 'Serviço Desc C',
                'produto_dm' => 'Serviço Desc M',
                'produto_dl' => 'Serviço Desc L',
                'produto_dt' => 'Serviço Desc T',
                'produto_vlr' => 550.00,
                'criador' => 1,
                'dthr_cr' => '2025-05-28 21:17:07',
                'modificador' => 1,
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            ## PRODUTO 5
            [
                'emp_id' => 1,
                'produto_id' => 5,
                'produto_sts' => 'AT',
                'produto_tipo' => 3,
                'partcp_pvlaor' => 100,
                'partcp_empid' => NULL,
                'partcp_seller' => NULL,
                'partcp_pgsplit' => NULL,
                'partcp_pgtransf' => 'X',
                'partcp_cdgbc' => 341,
                'partcp_agbc' => 1234,
                'partcp_ccbc' => '15656-0',
                'partcp_pix' => '13456df-192',
                'produto_ncm' => NULL,
                'produto_cdgb' => NULL,
                'produto_peso' => NULL,
                'produto_ctrl' => NULL,
                'produto_dc' => 'Teste Partic C',
                'produto_dm' => 'Teste Partic M',
                'produto_dl' => 'Teste Partic L',
                'produto_dt' => 'Teste Partic T',
                'produto_vlr' => 250.00,
                'criador' => 1,
                'dthr_cr' => '2025-05-28 21:17:07',
                'modificador' => 1,
                'dthr_ch' => '2025-05-28 21:17:07',
            ]
        ]);

        $tbdm_programa_pts = ProgramaPts::insert([
            ## PROGRAMA 1
            [
                'emp_id' => 1,
                'prgpts_id' => 1,
                'card_categ' => 'BRNZ',
                'prgpts_sts' => 'AT',
                'prgpts_valor' => 100.00,
                'prgpts_eq' => 15.00,
                'prgpts_sc' => NULL,
                'criador' => 1,
                'dthr_cr' => '2025-05-28 21:17:07',
                'modificador' => 1,
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            ## PROGRAMA 2
            [
                'emp_id' => 1,
                'prgpts_id' => 2,
                'card_categ' => 'OURO',
                'prgpts_sts' => 'AT',
                'prgpts_valor' => 200.00,
                'prgpts_eq' => 25.00,
                'prgpts_sc' => NULL,
                'criador' => 1,
                'dthr_cr' => '2025-05-28 21:17:07',
                'modificador' => 1,
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

            ## PROGRAMA 3
            [
                'emp_id' => 2,
                'prgpts_id' => 3,
                'card_categ' => 'OURO',
                'prgpts_sts' => 'AT',
                'prgpts_valor' => 200.00,
                'prgpts_eq' => 25.00,
                'prgpts_sc' => 'X',
                'criador' => 1,
                'dthr_cr' => '2025-05-28 21:17:07',
                'modificador' => 1,
                'dthr_ch' => '2025-05-28 21:17:07',
            ],

        ]);

        $tbtr_agendamento = [
            'id' =>    1,
            'agendamento_tipo' =>    2,
            'cliente_id' =>    1,
            'user_id' =>    1,
            'prontuario_id' =>    1,
            'title' =>    'teste title',
            'description' =>    'teste',
            'date' =>    date_create()->format('Y-m-d'),
            'start' =>    date_create()->format('Y-m-d H:i:s'),
            'end' =>    date_create()->format('Y-m-d H:i:s'),
            'observacao' =>    'teste',
            'class_name' =>    NULL,
            'status' =>    'RE',
            'criador' =>    1,
            'dthr_cr' =>    date_create()->format('Y-m-d H:i:s'),
            'modificador' =>    1,
            'dthr_ch' =>    date_create()->format('Y-m-d H:i:s')
        ];

        DB::table('tbtr_agendamento')->insert($tbtr_agendamento);
    }
}
