<?php

namespace Database\Seeders;

use App\Models\Multban\Cliente\Cliente;
use App\Models\Multban\Cliente\ClienteCard;
use App\Models\Multban\Cliente\ClienteEmp;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DatabaseDbSysClientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->call([
            DadosMestreSeeder::class,
            CidadesSeed::class,
        ]);

        Cliente::insert([
            // # CLIENTE 1
            [
                'cliente_id'        => 1,
                'cliente_uuid'      => '4653269-654968-984654-9865',
                'cliente_tipo'      => 1,
                'cliente_doc'       => '38520037097',
                'cliente_pasprt'    => 'AB1234567',
                'cliente_sts'       => 'AT',
                'cliente_nome'      => 'Cliente Teste Nome',
                'cliente_nm_alt'    => 'Cliente Teste Alternativo',
                'cliente_nm_card'   => 'Cliente Teste Cartão',
                'cliente_email'     => 'cliente.teste@example.com',
                'cliente_email_s'   => 'cliente.teste@example.com',
                'cliente_cel'       => '11987654321',
                'cliente_cel_s'     => '11987654321',
                'cliente_telfixo'   => '1134567890',
                'cliente_rendam'    => '1000',
                'cliente_rdam_s'    => '1000',
                'cliente_dt_fech'   => 10,
                'cliente_cep'       => '12345678',
                'cliente_end'       => 'Rua Teste',
                'cliente_endnum'    => '123',
                'cliente_endcmp'    => 'Apto 1',
                'cliente_endbair'   => 'Bairro Teste',
                'cliente_endcid'    => 2201,
                'cliente_endest'    => 'SP',
                'cliente_endpais'   => 'BR',
                'cliente_cep_s'     => '12345678',
                'cliente_end_s'     => 'Rua Teste',
                'cliente_endnum_s'  => '123',
                'cliente_endcmp_s'  => 'Apto 1',
                'cliente_endbair_s' => 'Bairro Teste',
                'cliente_endcid_s'  => 2201,
                'cliente_endest_s'  => 'SP',
                'cliente_endpais_s' => 'BR',
                'cliente_score'     => 0,
                'cliente_lmt_sg'    => 0,
                'cliente_pass'      => '12345678',
                'criador'           => 1,
                'dthr_cr'           => '2025-05-28 21:17:07',
                'modificador'       => 1,
                'dthr_ch'           => '2025-05-28 21:17:07',
            ],

            // # CLIENTE 2
            [
                'cliente_id'        => 2,
                'cliente_uuid'      => '4653269-654968-984654-9866',
                'cliente_tipo'      => 1,
                'cliente_doc'       => '39804759055',
                'cliente_pasprt'    => 'AB11534567',
                'cliente_sts'       => 'MN',
                'cliente_nome'      => 'Cliente Teste 2 Nome',
                'cliente_nm_alt'    => 'Cliente Teste 2 Alternativo',
                'cliente_nm_card'   => 'Cliente Teste 2 Cartão',
                'cliente_email'     => 'cliente.teste2@example.com',
                'cliente_email_s'   => 'cliente.teste2@example.com',
                'cliente_cel'       => '11986478596',
                'cliente_cel_s'     => '11986478596',
                'cliente_telfixo'   => '1165987423',
                'cliente_rendam'    => '1500',
                'cliente_rdam_s'    => '1500',
                'cliente_dt_fech'   => 15,
                'cliente_cep'       => '12345678',
                'cliente_end'       => 'Rua Teste',
                'cliente_endnum'    => '123',
                'cliente_endcmp'    => 'Apto 1',
                'cliente_endbair'   => 'Bairro Teste',
                'cliente_endcid'    => 2201,
                'cliente_endest'    => 'SP',
                'cliente_endpais'   => 'BR',
                'cliente_cep_s'     => '12345678',
                'cliente_end_s'     => 'Rua Teste',
                'cliente_endnum_s'  => '123',
                'cliente_endcmp_s'  => 'Apto 1',
                'cliente_endbair_s' => 'Bairro Teste',
                'cliente_endcid_s'  => 2201,
                'cliente_endest_s'  => 'SP',
                'cliente_endpais_s' => 'BR',
                'cliente_score'     => 0,
                'cliente_lmt_sg'    => 0,
                'cliente_pass'      => '12345678',
                'criador'           => 1,
                'dthr_cr'           => '2025-05-28 21:17:07',
                'modificador'       => 1,
                'dthr_ch'           => '2025-05-28 21:17:07',
            ],

            // # CLIENTE 3
            [
                'cliente_id'        => 3,
                'cliente_uuid'      => '4653269-654968-984654-9867',
                'cliente_tipo'      => 1,
                'cliente_doc'       => '08970549030',
                'cliente_pasprt'    => 'AB11111567',
                'cliente_sts'       => 'AT',
                'cliente_nome'      => 'Cliente Teste 3 Nome',
                'cliente_nm_alt'    => 'Cliente Teste 3 Alternativo',
                'cliente_nm_card'   => 'Cliente Teste 3 Cartão',
                'cliente_email'     => 'cliente.teste3@example.com',
                'cliente_email_s'   => 'cliente.teste3@example.com',
                'cliente_cel'       => '11986478596',
                'cliente_cel_s'     => '11986478596',
                'cliente_telfixo'   => '1165987423',
                'cliente_rendam'    => '2500',
                'cliente_rdam_s'    => '2500',
                'cliente_dt_fech'   => 20,
                'cliente_cep'       => '12345678',
                'cliente_end'       => 'Rua Teste',
                'cliente_endnum'    => '123',
                'cliente_endcmp'    => 'Apto 1',
                'cliente_endbair'   => 'Bairro Teste',
                'cliente_endcid'    => 2201,
                'cliente_endest'    => 'SP',
                'cliente_endpais'   => 'BR',
                'cliente_cep_s'     => '12345678',
                'cliente_end_s'     => 'Rua Teste',
                'cliente_endnum_s'  => '123',
                'cliente_endcmp_s'  => 'Apto 1',
                'cliente_endbair_s' => 'Bairro Teste',
                'cliente_endcid_s'  => 2201,
                'cliente_endest_s'  => 'SP',
                'cliente_endpais_s' => 'BR',
                'cliente_score'     => 0,
                'cliente_lmt_sg'    => 0,
                'cliente_pass'      => '12345678',
                'criador'           => 1,
                'dthr_cr'           => '2025-05-28 21:17:07',
                'modificador'       => 1,
                'dthr_ch'           => '2025-05-28 21:17:07',
            ],

            // # CLIENTE 4
            [
                'cliente_id'        => 4,
                'cliente_uuid'      => '4653269-654968-984654-9868',
                'cliente_tipo'      => 1,
                'cliente_doc'       => '98146186084',
                'cliente_pasprt'    => 'AB11111567',
                'cliente_sts'       => 'AT',
                'cliente_nome'      => 'Cliente Teste 4 Nome',
                'cliente_nm_alt'    => 'Cliente Teste 4 Alternativo',
                'cliente_nm_card'   => 'Cliente Teste 4 Cartão',
                'cliente_email'     => 'cliente.teste4@example.com',
                'cliente_email_s'   => 'cliente.teste4@example.com',
                'cliente_cel'       => '11986478596',
                'cliente_cel_s'     => '11986478596',
                'cliente_telfixo'   => '1165987423',
                'cliente_rendam'    => '2500',
                'cliente_rdam_s'    => '2500',
                'cliente_dt_fech'   => 20,
                'cliente_cep'       => '12345678',
                'cliente_end'       => 'Rua Teste',
                'cliente_endnum'    => '123',
                'cliente_endcmp'    => 'Apto 1',
                'cliente_endbair'   => 'Bairro Teste',
                'cliente_endcid'    => 2201,
                'cliente_endest'    => 'SP',
                'cliente_endpais'   => 'BR',
                'cliente_cep_s'     => '12345678',
                'cliente_end_s'     => 'Rua Teste',
                'cliente_endnum_s'  => '123',
                'cliente_endcmp_s'  => 'Apto 1',
                'cliente_endbair_s' => 'Bairro Teste',
                'cliente_endcid_s'  => 2201,
                'cliente_endest_s'  => 'SP',
                'cliente_endpais_s' => 'BR',
                'cliente_score'     => 0,
                'cliente_lmt_sg'    => 0,
                'cliente_pass'      => '12345678',
                'criador'           => 1,
                'dthr_cr'           => '2025-05-28 21:17:07',
                'modificador'       => 1,
                'dthr_ch'           => '2025-05-28 21:17:07',
            ],
        ]);

        ClienteEmp::insert([
            // # CLIENTE EMP 1
            [
                'emp_id'         => 1,
                'cliente_id'     => 1,
                'cliente_uuid'   => '4653269-654968-984654-9865',
                'cliente_doc'    => '38520037097',
                'cliente_pasprt' => 'AB1234567',
                'cad_liberado'   => 'X',
                'criador'        => 1,
                'dthr_cr'        => '2025-05-28 21:17:07',
                'modificador'    => 1,
                'dthr_ch'        => '2025-05-28 21:17:07',
            ],

            // # CLIENTE EMP 2
            [
                'emp_id'         => 1,
                'cliente_id'     => 2,
                'cliente_uuid'   => '4653269-654968-984654-9866',
                'cliente_doc'    => '39804759055',
                'cliente_pasprt' => 'AB11534567',
                'cad_liberado'   => 'X',
                'criador'        => 1,
                'dthr_cr'        => '2025-05-28 21:17:07',
                'modificador'    => 1,
                'dthr_ch'        => '2025-05-28 21:17:07',
            ],

            // # CLIENTE EMP 3
            [
                'emp_id'         => 1,
                'cliente_id'     => 3,
                'cliente_uuid'   => '4653269-654968-984654-9867',
                'cliente_doc'    => '08970549030',
                'cliente_pasprt' => 'AB11111567',
                'cad_liberado'   => 'X',
                'criador'        => 1,
                'dthr_cr'        => '2025-05-28 21:17:07',
                'modificador'    => 1,
                'dthr_ch'        => '2025-05-28 21:17:07',
            ],

            // # CLIENTE EMP 4
            [
                'emp_id'         => 2,
                'cliente_id'     => 4,
                'cliente_uuid'   => '4653269-654968-984654-9868',
                'cliente_doc'    => '98146186084',
                'cliente_pasprt' => 'AB11111567',
                'cad_liberado'   => 'X',
                'criador'        => 1,
                'dthr_cr'        => '2025-05-28 21:17:07',
                'modificador'    => 1,
                'dthr_ch'        => '2025-05-28 21:17:07',
            ],
        ]);

        ClienteCard::insert([
            // # CLIENTE CARD 1
            [
                'emp_id'         => 1,
                'cliente_id'     => 1,
                'cliente_doc'    => '38520037097',
                'card_uuid'      => Str::uuid(),
                'cliente_cardn'  => '1111111111111111',
                'cliente_cardcv' => '111',
                'cliente_pasprt' => 'AB1234567',
                'card_sts'       => 'AT',
                'card_tp'        => 'POS',
                'card_mod'       => 'CRDT',
                'card_categ'     => 'OURO',
                'card_desc'      => 'Cartão de Teste',
                'card_saldo_vlr' => 1000.00,
                'card_limite'    => 1000.00,
                'card_pts_part'  => 100,
                'card_pts_fraq'  => 0,
                'card_pts_mult'  => 0,
                'card_pts_cash'  => 0,
                'card_pass'      => '1234',
                'criador'        => 1,
                'dthr_cr'        => '2025-05-28 21:17:07',
                'modificador'    => 1,
                'dthr_ch'        => '2025-05-28 21:17:07',
            ],

            // # CLIENTE CARD 2
            [
                'emp_id'         => 1,
                'cliente_id'     => 1,
                'cliente_doc'    => '38520037097',
                'card_uuid'      => Str::uuid(),
                'cliente_cardn'  => '1212121212121212',
                'cliente_cardcv' => '121',
                'cliente_pasprt' => 'AB1234567',
                'card_sts'       => 'AT',
                'card_tp'        => 'PRE',
                'card_mod'       => 'GIFT',
                'card_categ'     => null,
                'card_desc'      => 'Cartão de Teste',
                'card_saldo_vlr' => 100.00,
                'card_limite'    => 1000.00,
                'card_pts_part'  => 100,
                'card_pts_fraq'  => 0,
                'card_pts_mult'  => 0,
                'card_pts_cash'  => 0,
                'card_pass'      => '1234',
                'criador'        => 1,
                'dthr_cr'        => '2025-05-28 21:17:07',
                'modificador'    => 1,
                'dthr_ch'        => '2025-05-28 21:17:07',
            ],

            // # CLIENTE CARD 3
            [
                'emp_id'         => 2,
                'cliente_id'     => 1,
                'cliente_doc'    => '38520037097',
                'card_uuid'      => Str::uuid(),
                'cliente_cardn'  => '2211221122112211',
                'cliente_cardcv' => '221',
                'cliente_pasprt' => 'AB1234567',
                'card_sts'       => 'AT',
                'card_tp'        => 'POS',
                'card_mod'       => 'CRDT',
                'card_categ'     => 'PRTA',
                'card_desc'      => 'Cartão de Teste',
                'card_saldo_vlr' => 1000.00,
                'card_limite'    => 1000.00,
                'card_pts_part'  => 100,
                'card_pts_fraq'  => 0,
                'card_pts_mult'  => 0,
                'card_pts_cash'  => 0,
                'card_pass'      => '1234',
                'criador'        => 1,
                'dthr_cr'        => '2025-05-28 21:17:07',
                'modificador'    => 1,
                'dthr_ch'        => '2025-05-28 21:17:07',
            ],

            // # CLIENTE CARD 4
            [
                'emp_id'         => 1,
                'cliente_id'     => 2,
                'cliente_doc'    => '39804759055',
                'card_uuid'      => Str::uuid(),
                'cliente_cardn'  => '2222222222222222',
                'cliente_cardcv' => '222',
                'cliente_pasprt' => 'AB11534567',
                'card_sts'       => 'AT',
                'card_tp'        => 'POS',
                'card_mod'       => 'CRDT',
                'card_categ'     => 'OURO',
                'card_desc'      => 'Cartão de Teste',
                'card_saldo_vlr' => 100.00,
                'card_limite'    => 1000.00,
                'card_pts_part'  => 100,
                'card_pts_fraq'  => 0,
                'card_pts_mult'  => 0,
                'card_pts_cash'  => 0,
                'card_pass'      => '1234',
                'criador'        => 1,
                'dthr_cr'        => '2025-05-28 21:17:07',
                'modificador'    => 1,
                'dthr_ch'        => '2025-05-28 21:17:07',
            ],

            // # CLIENTE CARD 5
            [
                'emp_id'         => 1,
                'cliente_id'     => 3,
                'cliente_doc'    => '08970549030',
                'card_uuid'      => Str::uuid(),
                'cliente_cardn'  => '3333333333333333',
                'cliente_cardcv' => '333',
                'cliente_pasprt' => 'AB11111567',
                'card_sts'       => 'AT',
                'card_tp'        => 'POS',
                'card_mod'       => 'CRDT',
                'card_categ'     => 'OURO',
                'card_desc'      => 'Cartão de Teste',
                'card_saldo_vlr' => 100.00,
                'card_limite'    => 1000.00,
                'card_pts_part'  => 100,
                'card_pts_fraq'  => 0,
                'card_pts_mult'  => 0,
                'card_pts_cash'  => 0,
                'card_pass'      => '1234',
                'criador'        => 1,
                'dthr_cr'        => '2025-05-28 21:17:07',
                'modificador'    => 1,
                'dthr_ch'        => '2025-05-28 21:17:07',
            ],

            // # CLIENTE CARD 6
            [
                'emp_id'         => 2,
                'cliente_id'     => 4,
                'cliente_doc'    => '98146186084',
                'card_uuid'      => Str::uuid(),
                'cliente_cardn'  => '4444444444444444',
                'cliente_cardcv' => '444',
                'cliente_pasprt' => 'AB11111567',
                'card_sts'       => 'AT',
                'card_tp'        => 'POS',
                'card_mod'       => 'CRDT',
                'card_categ'     => 'OURO',
                'card_desc'      => 'Cartão de Teste',
                'card_saldo_vlr' => 100.00,
                'card_limite'    => 1000.00,
                'card_pts_part'  => 100,
                'card_pts_fraq'  => 0,
                'card_pts_mult'  => 0,
                'card_pts_cash'  => 0,
                'card_pass'      => '1234',
                'criador'        => 1,
                'dthr_cr'        => '2025-05-28 21:17:07',
                'modificador'    => 1,
                'dthr_ch'        => '2025-05-28 21:17:07',
            ],
        ]);

    }
}
